MANIPULANDO STRINGS

In [ ]:
# importando a biblioteca pandas
import pandas as pd
# lendo o arquivo CSV em um DataFrame
df = pd.read_csv('C:\\Users\\eleil\\OneDrive\\Documents\\GitHub\\Estudo-e-Projetos-Alura\\Python para Data Sciense\\Pandas\\Manipulação de Strings\\banco_clientes.csv')
df

                 nome                               endereco         telefone
0        Paulo Hammer        Rua 22 de Abril, 52614-524 1234    11 99548-2578
1      JonaS da Silva    Rua Alvarenga Borges, 573 29285-678    11 99999-1234
2        Maria Santos         Av. Bom Sucesso 1283 87654-321    11 98765-4321
3   pedro albuquerque             Rua Colombo, 789 45678-912    11 91234-5678
4        ana oliveira          Rua Dinamarca, 1011 34567-890    11 99876-5432
5      José Fernandes            Av. Ermeson, 23456-789 1213  (11) 97654-3210
6     mariana castro            Rua das Flores, 15 56789-123    11 95555-6789
7         LUCAS SOUZA         Av. Governador, 1617 67890-234    11 94444-5678
8        Carla santos         Rua Helio Gracie, 19 78901-345    11 93333-4567
9      Felipe Martins      Av. 28 de Novembro, 221 89012-456  (11) 92222-7890
10     Amanda Pereira                Rua Joana 423 90123-567    11 91111-2345
11       Rafaela Lima              Av. Brasil, 245 01234-567  (11) 90000-5678
12      Eduardo Silva        Rua do Lamparao, 2627 12345-678  (11) 98888-9012
13  Gustavo Rodrigues       Rua do Chuvisco , 2829 23456-789  (11) 97777-2345
14     Fernanda Costa           Av. Goytacaz, 3031 34567-890    11 96666-5678
15      Renato Santos        Av. Areia Negra, 45678-912 3233  (11) 95555-9012
16    Letícia Ribeiro      Rua das Palmeiras, 3435 56789-123    11 94444-2345
17        Maria Silva              Av. Oliva, 3637 67890-234  (11) 93333-5678
18   Isabela Oliveira               Rua Peri , 339 78901-345    11 92222-9012
19        Bruno Costa           Av. Balestrin 1337 89012-456    11 91111-2345
20     Vanessa Santos  Rua Nicolau Copérnico, 90123-567 1543  (11) 90000-5678

In [ ]:
# convertendo os valores da coluna 'nome' para letras maiúsculas
df['nome'] = df['nome'].str.upper()
df

"""O método str.upper() do pandas é utilizado para converter todos os caracteres de uma série de strings para letras maiúsculas. No exemplo acima, estamos aplicando str.upper() à coluna 'nome' do DataFrame df. Isso é útil quando queremos padronizar o formato dos dados textuais, facilitando comparações e análises posteriores. O resultado é que todos os nomes na coluna 'nome' serão exibidos em letras maiúsculas."""

                 nome                               endereco         telefone
0        PAULO HAMMER        Rua 22 de Abril, 52614-524 1234    11 99548-2578
1      JONAS DA SILVA    Rua Alvarenga Borges, 573 29285-678    11 99999-1234
2        MARIA SANTOS         Av. Bom Sucesso 1283 87654-321    11 98765-4321
3   PEDRO ALBUQUERQUE             Rua Colombo, 789 45678-912    11 91234-5678
4        ANA OLIVEIRA          Rua Dinamarca, 1011 34567-890    11 99876-5432
5      JOSÉ FERNANDES            Av. Ermeson, 23456-789 1213  (11) 97654-3210
6     MARIANA CASTRO            Rua das Flores, 15 56789-123    11 95555-6789
7         LUCAS SOUZA         Av. Governador, 1617 67890-234    11 94444-5678
8        CARLA SANTOS         Rua Helio Gracie, 19 78901-345    11 93333-4567
9      FELIPE MARTINS      Av. 28 de Novembro, 221 89012-456  (11) 92222-7890
10     AMANDA PEREIRA                Rua Joana 423 90123-567    11 91111-2345
11       RAFAELA LIMA              Av. Brasil, 245 01234-567  (11) 90000-5678
12      EDUARDO SILVA        Rua do Lamparao, 2627 12345-678  (11) 98888-9012
13  GUSTAVO RODRIGUES       Rua do Chuvisco , 2829 23456-789  (11) 97777-2345
14     FERNANDA COSTA           Av. Goytacaz, 3031 34567-890    11 96666-5678
15      RENATO SANTOS        Av. Areia Negra, 45678-912 3233  (11) 95555-9012
16    LETÍCIA RIBEIRO      Rua das Palmeiras, 3435 56789-123    11 94444-2345
17        MARIA SILVA              Av. Oliva, 3637 67890-234  (11) 93333-5678
18   ISABELA OLIVEIRA               Rua Peri , 339 78901-345    11 92222-9012
19        BRUNO COSTA           Av. Balestrin 1337 89012-456    11 91111-2345
20     VANESSA SANTOS  Rua Nicolau Copérnico, 90123-567 1543  (11) 90000-5678

In [9]:
# removendo os parênteses da coluna 'telefone'
df['telefone'] = df['telefone'].str.replace("(","", regex=False).str.replace(")","", regex=False)
df

"""O metodo str.replace() do pandas é utilizado para substituir substrings em uma série de strings. No exemplo acima, estamos aplicando str.replace("(","", regex=False) e str.replace(")","", regex=False) à coluna 'telefone' do DataFrame df para remover os parênteses. O argumento regex=False indica que estamos tratando as strings literalmente, sem usar expressões regulares. Isso é útil quando queremos limpar ou padronizar os dados textuais, como números de telefone, removendo caracteres indesejados. O resultado é que todos os parênteses serão removidos dos valores na coluna 'telefone'."""

'O metodo str.replace() do pandas é utilizado para substituir substrings em uma série de strings. No exemplo acima, estamos aplicando str.replace("(","", regex=False) e str.replace(")","", regex=False) à coluna \'telefone\' do DataFrame df para remover os parênteses. O argumento regex=False indica que estamos tratando as strings literalmente, sem usar expressões regulares. Isso é útil quando queremos limpar ou padronizar os dados textuais, como números de telefone, removendo caracteres indesejados. O resultado é que todos os parênteses serão removidos dos valores na coluna \'telefone\'.'

In [ ]:
# extraindo os códigos postais da coluna 'endereco'
df.endereco.str.extract("(\d{5}-\d{3})")


"""O metodo str.extract() do pandas é utilizado para extrair substrings de uma série de strings com base em uma expressão regular. No exemplo acima, estamos aplicando str.extract("(\d{5}-\d{3})") à coluna 'endereco' do DataFrame df para extrair os códigos postais no formato 'XXXXX-XXX'. A expressão regular (\d{5}-\d{3}) corresponde a cinco dígitos seguidos por um hífen e mais três dígitos. Isso é útil quando queremos isolar informações específicas contidas em uma string maior, facilitando a análise e manipulação dos dados. O resultado é uma nova coluna 'cep' contendo apenas os códigos postais extraídos da coluna 'endereco'."""

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
C:\Users\eleil\AppData\Local\Temp\ipykernel_4840\946417237.py:2: SyntaxWarning: invalid escape sequence '\d'
  df.endereco.str.extract("(\d{5}-\d{3})")

            0
0   52614-524
1   29285-678
2   87654-321
3   45678-912
4   34567-890
5   23456-789
6   56789-123
7   67890-234
8   78901-345
9   89012-456
10  90123-567
11  01234-567
12  12345-678
13  23456-789
14  34567-890
15  45678-912
16  56789-123
17  67890-234
18  78901-345
19  89012-456
20  90123-567

In [ ]:
df['cep'] = df.endereco.str.extract("(\d{5}-\d{3})")
df

"""O metodo str.extract() do pandas é utilizado para extrair substrings de uma série de strings com base em uma expressão regular. No exemplo acima, estamos aplicando str.extract("(\d{5}-\d{3})") à coluna 'endereco' do DataFrame df para extrair os códigos postais no formato 'XXXXX-XXX'. A expressão regular (\d{5}-\d{3}) corresponde a cinco dígitos seguidos por um hífen e mais três dígitos. Isso é útil quando queremos isolar informações específicas contidas em uma string maior, facilitando a análise e manipulação dos dados. O resultado é uma nova coluna 'cep' contendo apenas os códigos postais extraídos da coluna 'endereco'."""

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\eleil\AppData\Local\Temp\ipykernel_4840\4166122777.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['cep'] = df.endereco.str.extract("(\d{5}-\d{3})")

,nome,endereco,telefone,endereco_numero,cep
0,PAULO HAMMER,"Rua 22 de Abril, 52614-524 1234",11 99548-2578,52614-524,52614-524
1,JONAS DA SILVA,"Rua Alvarenga Borges, 573 29285-678",11 99999-1234,29285-678,29285-678
2,MARIA SANTOS,Av. Bom Sucesso 1283 87654-321,11 98765-4321,87654-321,87654-321
3,PEDRO ALBUQUERQUE,"Rua Colombo, 789 45678-912",11 91234-5678,45678-912,45678-912
4,ANA OLIVEIRA,"Rua Dinamarca, 1011 34567-890",11 99876-5432,34567-890,34567-890
5,JOSÉ FERNANDES,"Av. Ermeson, 23456-789 1213",11 97654-3210,23456-789,23456-789
6,MARIANA CASTRO,"Rua das Flores, 15 56789-123",11 95555-6789,56789-123,56789-123
7,LUCAS SOUZA,"Av. Governador, 1617 67890-234",11 94444-5678,67890-234,67890-234
8,CARLA SANTOS,"Rua Helio Gracie, 19 78901-345",11 93333-4567,78901-345,78901-345
9,FELIPE MARTINS,"Av. 28 de Novembro, 221 89012-456",11 92222-7890,89012-456,89012-456
10,AMANDA PEREIRA,Rua Joana 423 90123-567,11 91111-2345,90123-567,90123-567
11,RAFAELA LIMA,"Av. Brasil, 245 01234-567",11 90000-5678,01234-567,01234-567
12,EDUARDO SILVA,"Rua do Lamparao, 2627 12345-678",11 98888-9012,12345-678,12345-678
13,GUSTAVO RODRIGUES,"Rua do Chuvisco , 2829 23456-789",11 97777-2345,23456-789,23456-789
14,FERNANDA COSTA,"Av. Goytacaz, 3031 34567-890",11 96666-5678,34567-890,34567-890
15,RENATO SANTOS,"Av. Areia Negra, 45678-912 3233",11 95555-9012,45678-912,45678-912
16,LETÍCIA RIBEIRO,"Rua das Palmeiras, 3435 56789-123",11 94444-2345,56789-123,56789-123
17,MARIA SILVA,"Av. Oliva, 3637 67890-234",11 93333-5678,67890-234,67890-234
18,ISABELA OLIVEIRA,"Rua Peri , 339 78901-345",11 92222-9012,78901-345,78901-345
19,BRUNO COSTA,Av. Balestrin 1337 89012-456,11 91111-2345,89012-456,89012-456
20,VANESSA SANTOS,"Rua Nicolau Copérnico, 90123-567 1543",11 90000-5678,90123-567,90123-567

In [ ]:
# removendo a coluna 'endereco_numero' do DataFrame
df = df.drop('endereco_numero', axis=1)
df

"""O método drop() do pandas é utilizado para remover colunas ou linhas de um DataFrame. No exemplo acima, estamos removendo a coluna 'endereco_numero' do DataFrame df, especificando axis=1 para indicar que queremos remover uma coluna (axis=0 seria para remover uma linha). Isso é útil quando queremos eliminar dados desnecessários ou irrelevantes para nossa análise. O resultado é um DataFrame atualizado sem a coluna 'endereco_numero'."""

,nome,endereco,telefone,cep
0,PAULO HAMMER,"Rua 22 de Abril, 52614-524 1234",11 99548-2578,52614-524
1,JONAS DA SILVA,"Rua Alvarenga Borges, 573 29285-678",11 99999-1234,29285-678
2,MARIA SANTOS,Av. Bom Sucesso 1283 87654-321,11 98765-4321,87654-321
3,PEDRO ALBUQUERQUE,"Rua Colombo, 789 45678-912",11 91234-5678,45678-912
4,ANA OLIVEIRA,"Rua Dinamarca, 1011 34567-890",11 99876-5432,34567-890
5,JOSÉ FERNANDES,"Av. Ermeson, 23456-789 1213",11 97654-3210,23456-789
6,MARIANA CASTRO,"Rua das Flores, 15 56789-123",11 95555-6789,56789-123
7,LUCAS SOUZA,"Av. Governador, 1617 67890-234",11 94444-5678,67890-234
8,CARLA SANTOS,"Rua Helio Gracie, 19 78901-345",11 93333-4567,78901-345
9,FELIPE MARTINS,"Av. 28 de Novembro, 221 89012-456",11 92222-7890,89012-456
10,AMANDA PEREIRA,Rua Joana 423 90123-567,11 91111-2345,90123-567
11,RAFAELA LIMA,"Av. Brasil, 245 01234-567",11 90000-5678,01234-567
12,EDUARDO SILVA,"Rua do Lamparao, 2627 12345-678",11 98888-9012,12345-678
13,GUSTAVO RODRIGUES,"Rua do Chuvisco , 2829 23456-789",11 97777-2345,23456-789
14,FERNANDA COSTA,"Av. Goytacaz, 3031 34567-890",11 96666-5678,34567-890
15,RENATO SANTOS,"Av. Areia Negra, 45678-912 3233",11 95555-9012,45678-912
16,LETÍCIA RIBEIRO,"Rua das Palmeiras, 3435 56789-123",11 94444-2345,56789-123
17,MARIA SILVA,"Av. Oliva, 3637 67890-234",11 93333-5678,67890-234
18,ISABELA OLIVEIRA,"Rua Peri , 339 78901-345",11 92222-9012,78901-345
19,BRUNO COSTA,Av. Balestrin 1337 89012-456,11 91111-2345,89012-456
20,VANESSA SANTOS,"Rua Nicolau Copérnico, 90123-567 1543",11 90000-5678,90123-567

In [ ]:
# removendo os códigos postais da coluna 'endereco'
df.endereco.str.replace("(\d{5}-\d{3})","", regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\eleil\AppData\Local\Temp\ipykernel_4840\3046173180.py:1: SyntaxWarning: invalid escape sequence '\d'
  df.endereco.str.replace("(\d{5}-\d{3})","", regex=True)

0           Rua 22 de Abril,  1234
1       Rua Alvarenga Borges, 573
2            Av. Bom Sucesso 1283
3                Rua Colombo, 789
4             Rua Dinamarca, 1011
5               Av. Ermeson,  1213
6              Rua das Flores, 15
7            Av. Governador, 1617
8            Rua Helio Gracie, 19
9         Av. 28 de Novembro, 221
10                  Rua Joana 423
11                Av. Brasil, 245
12          Rua do Lamparao, 2627
13         Rua do Chuvisco , 2829
14             Av. Goytacaz, 3031
15          Av. Areia Negra,  3233
16        Rua das Palmeiras, 3435
17                Av. Oliva, 3637
18                 Rua Peri , 339
19             Av. Balestrin 1337
20    Rua Nicolau Copérnico,  1543
Name: endereco, dtype: object

In [ ]:
# atribuindo o resultado da remoção dos códigos postais de volta à coluna 'endereco' e removendo espaços extras
df['endereco'] = df.endereco.str.replace("(\d{5}-\d{3})","", regex=True).str.strip()
df

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\eleil\AppData\Local\Temp\ipykernel_4840\3549009207.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['endereco'] = df.endereco.str.replace("(\d{5}-\d{3})","", regex=True).str.strip()

                 nome                      endereco       telefone        cep
0        PAULO HAMMER        Rua 22 de Abril,  1234  11 99548-2578  52614-524
1      JONAS DA SILVA     Rua Alvarenga Borges, 573  11 99999-1234  29285-678
2        MARIA SANTOS          Av. Bom Sucesso 1283  11 98765-4321  87654-321
3   PEDRO ALBUQUERQUE              Rua Colombo, 789  11 91234-5678  45678-912
4        ANA OLIVEIRA           Rua Dinamarca, 1011  11 99876-5432  34567-890
5      JOSÉ FERNANDES            Av. Ermeson,  1213  11 97654-3210  23456-789
6     MARIANA CASTRO             Rua das Flores, 15  11 95555-6789  56789-123
7         LUCAS SOUZA          Av. Governador, 1617  11 94444-5678  67890-234
8        CARLA SANTOS          Rua Helio Gracie, 19  11 93333-4567  78901-345
9      FELIPE MARTINS       Av. 28 de Novembro, 221  11 92222-7890  89012-456
10     AMANDA PEREIRA                 Rua Joana 423  11 91111-2345  90123-567
11       RAFAELA LIMA               Av. Brasil, 245  11 90000-5678  01234-567
12      EDUARDO SILVA         Rua do Lamparao, 2627  11 98888-9012  12345-678
13  GUSTAVO RODRIGUES        Rua do Chuvisco , 2829  11 97777-2345  23456-789
14     FERNANDA COSTA            Av. Goytacaz, 3031  11 96666-5678  34567-890
15      RENATO SANTOS        Av. Areia Negra,  3233  11 95555-9012  45678-912
16    LETÍCIA RIBEIRO       Rua das Palmeiras, 3435  11 94444-2345  56789-123
17        MARIA SILVA               Av. Oliva, 3637  11 93333-5678  67890-234
18   ISABELA OLIVEIRA                Rua Peri , 339  11 92222-9012  78901-345
19        BRUNO COSTA            Av. Balestrin 1337  11 91111-2345  89012-456
20     VANESSA SANTOS  Rua Nicolau Copérnico,  1543  11 90000-5678  90123-567

In [ ]:
# Removendo a vergula da coluna 'endereco' e dividindo a coluna 'endereco' em duas novas colunas: 'rua' e 'numero'
df.endereco.str.replace(",","").str.split('\s(?=\d+$)', expand=True)

"""O método str.replace() do pandas é utilizado para substituir substrings em uma série de strings. No exemplo acima, estamos aplicando str.replace(",","") à coluna 'endereco' do DataFrame df para remover as vírgulas. Em seguida, usamos str.split('\s(?=\d+$)', expand=True) para dividir a coluna 'endereco' em duas novas colunas: 'rua' e 'numero'. A expressão regular '\s(?=\d+$)' é usada para identificar o espaço que precede o número no final da string. O argumento expand=True indica que queremos expandir o resultado em várias colunas. Isso é útil quando queremos separar informações contidas em uma única coluna para facilitar a análise e manipulação dos dados. O resultado é um DataFrame com as colunas 'rua' e 'numero' separadas.

O metodo str.split() do pandas é utilizado para dividir strings em uma série de substrings com base em um delimitador especificado. No exemplo acima, estamos usando str.split('\s(?=\d+$)', expand=True) para dividir a coluna 'endereco' do DataFrame df em duas novas colunas: 'rua' e 'numero'. A expressão regular '\s(?=\d+$)' identifica o espaço que precede o número no final da string, permitindo que a divisão ocorra nesse ponto específico. O argumento expand=True indica que queremos expandir o resultado em várias colunas. Isso é útil quando queremos separar informações contidas em uma única coluna para facilitar a análise e manipulação dos dados. O resultado é um DataFrame com as colunas 'rua' e 'numero' separadas."""

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
C:\Users\eleil\AppData\Local\Temp\ipykernel_4840\3771588527.py:2: SyntaxWarning: invalid escape sequence '\s'
  df.endereco.str.replace(",","").str.split('\s(?=\d+$)', expand=True)

                         0     1
0         Rua 22 de Abril   1234
1     Rua Alvarenga Borges   573
2          Av. Bom Sucesso  1283
3              Rua Colombo   789
4            Rua Dinamarca  1011
5             Av. Ermeson   1213
6           Rua das Flores    15
7           Av. Governador  1617
8         Rua Helio Gracie    19
9       Av. 28 de Novembro   221
10               Rua Joana   423
11              Av. Brasil   245
12         Rua do Lamparao  2627
13        Rua do Chuvisco   2829
14            Av. Goytacaz  3031
15        Av. Areia Negra   3233
16       Rua das Palmeiras  3435
17               Av. Oliva  3637
18               Rua Peri    339
19           Av. Balestrin  1337
20  Rua Nicolau Copérnico   1543

In [ ]:
# atribuindo as novas colunas 'rua' e 'numero' ao DataFrame
df[['rua', 'numero']] = df.endereco.str.replace(",","").str.split('\s(?=\d+$)', regex=True, expand=True)
df

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\eleil\AppData\Local\Temp\ipykernel_4840\1271967991.py:1: SyntaxWarning: invalid escape sequence '\s'
  df[['rua', 'numero']] = df.endereco.str.replace(",","").str.split('\s(?=\d+$)', regex=True, expand=True)

,nome,endereco,telefone,cep,rua,numero
0,PAULO HAMMER,"Rua 22 de Abril, 1234",11 99548-2578,52614-524,Rua 22 de Abril,1234
1,JONAS DA SILVA,"Rua Alvarenga Borges, 573",11 99999-1234,29285-678,Rua Alvarenga Borges,573
2,MARIA SANTOS,Av. Bom Sucesso 1283,11 98765-4321,87654-321,Av. Bom Sucesso,1283
3,PEDRO ALBUQUERQUE,"Rua Colombo, 789",11 91234-5678,45678-912,Rua Colombo,789
4,ANA OLIVEIRA,"Rua Dinamarca, 1011",11 99876-5432,34567-890,Rua Dinamarca,1011
5,JOSÉ FERNANDES,"Av. Ermeson, 1213",11 97654-3210,23456-789,Av. Ermeson,1213
6,MARIANA CASTRO,"Rua das Flores, 15",11 95555-6789,56789-123,Rua das Flores,15
7,LUCAS SOUZA,"Av. Governador, 1617",11 94444-5678,67890-234,Av. Governador,1617
8,CARLA SANTOS,"Rua Helio Gracie, 19",11 93333-4567,78901-345,Rua Helio Gracie,19
9,FELIPE MARTINS,"Av. 28 de Novembro, 221",11 92222-7890,89012-456,Av. 28 de Novembro,221
10,AMANDA PEREIRA,Rua Joana 423,11 91111-2345,90123-567,Rua Joana,423
11,RAFAELA LIMA,"Av. Brasil, 245",11 90000-5678,01234-567,Av. Brasil,245
12,EDUARDO SILVA,"Rua do Lamparao, 2627",11 98888-9012,12345-678,Rua do Lamparao,2627
13,GUSTAVO RODRIGUES,"Rua do Chuvisco , 2829",11 97777-2345,23456-789,Rua do Chuvisco,2829
14,FERNANDA COSTA,"Av. Goytacaz, 3031",11 96666-5678,34567-890,Av. Goytacaz,3031
15,RENATO SANTOS,"Av. Areia Negra, 3233",11 95555-9012,45678-912,Av. Areia Negra,3233
16,LETÍCIA RIBEIRO,"Rua das Palmeiras, 3435",11 94444-2345,56789-123,Rua das Palmeiras,3435
17,MARIA SILVA,"Av. Oliva, 3637",11 93333-5678,67890-234,Av. Oliva,3637
18,ISABELA OLIVEIRA,"Rua Peri , 339",11 92222-9012,78901-345,Rua Peri,339
19,BRUNO COSTA,Av. Balestrin 1337,11 91111-2345,89012-456,Av. Balestrin,1337
20,VANESSA SANTOS,"Rua Nicolau Copérnico, 1543",11 90000-5678,90123-567,Rua Nicolau Copérnico,1543

In [ ]:
# removendo a coluna 'endereco' do DataFrame
df = df.drop('endereco', axis=1)
df

"""O metodo drop() do pandas é utilizado para remover colunas ou linhas de um DataFrame. No exemplo acima, estamos removendo a coluna 'endereco' do DataFrame df, especificando axis=1 para indicar que queremos remover uma coluna (axis=0 seria para remover uma linha). Isso é útil quando queremos eliminar dados desnecessários ou irrelevantes para nossa análise. O resultado é um DataFrame atualizado sem a coluna 'endereco'."""

                 nome       telefone        cep                     rua numero
0        PAULO HAMMER  11 99548-2578  52614-524        Rua 22 de Abril    1234
1      JONAS DA SILVA  11 99999-1234  29285-678    Rua Alvarenga Borges    573
2        MARIA SANTOS  11 98765-4321  87654-321         Av. Bom Sucesso   1283
3   PEDRO ALBUQUERQUE  11 91234-5678  45678-912             Rua Colombo    789
4        ANA OLIVEIRA  11 99876-5432  34567-890           Rua Dinamarca   1011
5      JOSÉ FERNANDES  11 97654-3210  23456-789            Av. Ermeson    1213
6     MARIANA CASTRO   11 95555-6789  56789-123          Rua das Flores     15
7         LUCAS SOUZA  11 94444-5678  67890-234          Av. Governador   1617
8        CARLA SANTOS  11 93333-4567  78901-345        Rua Helio Gracie     19
9      FELIPE MARTINS  11 92222-7890  89012-456      Av. 28 de Novembro    221
10     AMANDA PEREIRA  11 91111-2345  90123-567               Rua Joana    423
11       RAFAELA LIMA  11 90000-5678  01234-567              Av. Brasil    245
12      EDUARDO SILVA  11 98888-9012  12345-678         Rua do Lamparao   2627
13  GUSTAVO RODRIGUES  11 97777-2345  23456-789        Rua do Chuvisco    2829
14     FERNANDA COSTA  11 96666-5678  34567-890            Av. Goytacaz   3031
15      RENATO SANTOS  11 95555-9012  45678-912        Av. Areia Negra    3233
16    LETÍCIA RIBEIRO  11 94444-2345  56789-123       Rua das Palmeiras   3435
17        MARIA SILVA  11 93333-5678  67890-234               Av. Oliva   3637
18   ISABELA OLIVEIRA  11 92222-9012  78901-345               Rua Peri     339
19        BRUNO COSTA  11 91111-2345  89012-456           Av. Balestrin   1337
20     VANESSA SANTOS  11 90000-5678  90123-567  Rua Nicolau Copérnico    1543