CONHECENDO OS DADOS

In [1]:
# importando as bibliotecas necessarias para o tratamento dos dados
import pandas as pd
import numpy as np

In [2]:
# lendo o arquivo json com os dados de churn
dados_churn = pd.read_json('C:\\Users\\eleil\\OneDrive\\Documents\\GitHub\\Estudo-e-Projetos-Alura\\Python para Data Sciense\\Pandas\\Limpeza e tratamento de dados\\dataset-telecon.json')
dados_churn.head()

"""O termo churn é utilizado para descrever a rotatividade de clientes em um determinado período. Em outras palavras, refere-se à taxa na qual os clientes deixam de usar os serviços ou produtos de uma empresa. O churn é uma métrica crucial para empresas, especialmente aquelas que operam em setores como telecomunicações, serviços de assinatura, e-commerce e outros mercados competitivos."""

'O termo churn é utilizado para descrever a rotatividade de clientes em um determinado período. Em outras palavras, refere-se à taxa na qual os clientes deixam de usar os serviços ou produtos de uma empresa. O churn é uma métrica crucial para empresas, especialmente aquelas que operam em setores como telecomunicações, serviços de assinatura, e-commerce e outros mercados competitivos.'

In [3]:
# mostrando o valor da primeira conta na base de dados
dados_churn['conta'][0]

{'contrato': None,
 'faturamente_eletronico': None,
 'metodo_pagamento': None,
 'cobranca': {'mensal': None, 'Total': None}}

In [4]:
# normalizando os dados da coluna conta
pd.json_normalize(dados_churn['conta']).head()

"""O metodo json_normalize do pandas é utilizado para "achatar" estruturas de dados JSON aninhadas em um DataFrame plano. Isso é especialmente útil quando você está lidando com dados JSON que contêm listas ou dicionários dentro de outros dicionários, e você deseja transformar esses dados em um formato tabular para facilitar a análise."""

'O metodo json_normalize do pandas é utilizado para "achatar" estruturas de dados JSON aninhadas em um DataFrame plano. Isso é especialmente útil quando você está lidando com dados JSON que contêm listas ou dicionários dentro de outros dicionários, e você deseja transformar esses dados em um formato tabular para facilitar a análise.'

In [5]:
# valor da primeira linha da coluna telefone
pd.json_normalize(dados_churn['telefone']).head()

  servico_telefone varias_linhas
0              sim           nao
1              sim           sim
2              sim           nao
3              sim           nao
4              sim           nao

Transformando dados em uma DataFrame

In [6]:
# impoirtando a biblioteca json para manipulação direta do arquivo json
import json
# lendo o arquivo json diretamente
with open('C:\\Users\\eleil\\OneDrive\\Documents\\GitHub\\Estudo-e-Projetos-Alura\\Python para Data Sciense\\Pandas\\Limpeza e tratamento de dados\\dataset-telecon.json') as f:
    json_bruto = json.load(f)
json_bruto  

"""O metodo with open() é utilizado para abrir arquivos em Python de forma segura e eficiente. Ele garante que o arquivo seja corretamente fechado após o uso, mesmo que ocorra um erro durante a manipulação do arquivo. A sintaxe básica é "with open('caminho/do/arquivo', 'modo') as variavel:", onde 'caminho/do/arquivo' é o caminho para o arquivo que você deseja abrir, 'modo' especifica como o arquivo será aberto (por exemplo, 'r' para leitura, 'w' para escrita, etc.), e 'variavel' é o nome da variável que você usará para interagir com o arquivo dentro do bloco "with".

O metodo json.load() da biblioteca json do Python é utilizado para ler dados JSON a partir de um arquivo ou de uma string e convertê-los em objetos Python correspondentes, como dicionários ou listas. Isso permite que você trabalhe com dados JSON de forma mais fácil e eficiente dentro do seu código Python."""

'O metodo with open() é utilizado para abrir arquivos em Python de forma segura e eficiente. Ele garante que o arquivo seja corretamente fechado após o uso, mesmo que ocorra um erro durante a manipulação do arquivo. A sintaxe básica é "with open(\'caminho/do/arquivo\', \'modo\') as variavel:", onde \'caminho/do/arquivo\' é o caminho para o arquivo que você deseja abrir, \'modo\' especifica como o arquivo será aberto (por exemplo, \'r\' para leitura, \'w\' para escrita, etc.), e \'variavel\' é o nome da variável que você usará para interagir com o arquivo dentro do bloco "with".\n\nO metodo json.load() da biblioteca json do Python é utilizado para ler dados JSON a partir de um arquivo ou de uma string e convertê-los em objetos Python correspondentes, como dicionários ou listas. Isso permite que você trabalhe com dados JSON de forma mais fácil e eficiente dentro do seu código Python.'

In [7]:
# Transformando dados em uma DataFrame
dados_normalizados = pd.json_normalize(json_bruto)
dados_normalizados.head()

"""O metodo json_normalize do pandas é utilizado para "achatar" estruturas de dados JSON aninhadas em um DataFrame plano. Isso é especialmente útil quando você está lidando com dados JSON que contêm listas ou dicionários dentro de outros dicionários, e você deseja transformar esses dados em um formato tabular para facilitar a análise."""

'O metodo json_normalize do pandas é utilizado para "achatar" estruturas de dados JSON aninhadas em um DataFrame plano. Isso é especialmente útil quando você está lidando com dados JSON que contêm listas ou dicionários dentro de outros dicionários, e você deseja transformar esses dados em um formato tabular para facilitar a análise.'

Transformação inicial dos dados

In [8]:
# viIsualizando as informações gerais do DataFrame
dados_normalizados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7344 entries, 0 to 7343
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id_cliente                     7344 non-null   object
 1   Churn                          7344 non-null   object
 2   cliente.genero                 7344 non-null   object
 3   cliente.idoso                  7344 non-null   int64
 4   cliente.parceiro               7344 non-null   object
 5   cliente.dependentes            7344 non-null   object
 6   cliente.tempo_servico          7336 non-null   float64
 7   telefone.servico_telefone      7344 non-null   object
 8   telefone.varias_linhas         7344 non-null   object
 9   internet.servico_internet      7344 non-null   object
 10  internet.seguranca_online      7344 non-null   object
 11  internet.backup_online         7344 non-null   object
 12  internet.protecao_dispositivo  7344 non-null   object
 13  internet.suporte_tecnico       7344 non-null   object
 14  internet.tv_streaming          7344 non-null   object
 15  internet.filmes_streaming      7344 non-null   object
 16  conta.contrato                 7312 non-null   object
 17  conta.faturamente_eletronico   7326 non-null   object
 18  conta.metodo_pagamento         7317 non-null   object
 19  conta.cobranca.mensal          7326 non-null   float64
 20  conta.cobranca.Total           7328 non-null   object
dtypes: float64(2), int64(1), object(18)
memory usage: 1.2+ MB

In [9]:
# Erro ao tentar converter a coluna 'conta.cobranca.Total' para float64 devido a presença de valores não numéricos
# Convertendo a coluna 'conta.cobranca.Total' para float64, tratando erros
dados_normalizados['conta.cobranca.Total'] = dados_normalizados['conta.cobranca.Total'].astype('float64')

ValueError: could not convert string to float: ' '

In [10]:
# visualizando os valores que não foram convertidos na coluna 'conta.cobranca.Total'
dados_normalizados[dados_normalizados['conta.cobranca.Total'] == ' '].head()

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
975,1371-DWPAZ,nao,feminino,0,sim,sim,0.0,nao,sem servico de telefone,DSL,...,sim,sim,sim,sim,nao,dois anos,nao,cartao de credito (automatico),56.05,
1775,2520-SGTTA,nao,feminino,0,sim,sim,0.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,dois anos,nao,cheque pelo correio,20.00,
1955,2775-SEFEE,nao,masculino,0,nao,sim,0.0,sim,sim,DSL,...,sim,nao,sim,nao,nao,dois anos,sim,transferencia bancaria (automatica),61.90,
2075,2923-ARZLG,nao,masculino,0,sim,sim,0.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,dois anos,sim,cheque pelo correio,19.70,
2232,3115-CZMZD,nao,masculino,0,nao,sim,0.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,dois anos,nao,cheque pelo correio,20.25,

In [11]:
# mostrando todas as colunas dos registros que não foram convertidos na coluna 'conta.cobranca.Total'
dados_normalizados[dados_normalizados['conta.cobranca.Total'] == ' '][
    ['cliente.tempo_servico', 'conta.contrato', 'conta.cobranca.mensal', 'conta.cobranca.Total']
]

,cliente.tempo_servico,conta.contrato,conta.cobranca.mensal,conta.cobranca.Total
975,0.0,dois anos,56.05,
1775,0.0,dois anos,20.00,
1955,0.0,dois anos,61.90,
2075,0.0,dois anos,19.70,
2232,0.0,dois anos,20.25,
2308,0.0,dois anos,25.35,
2930,0.0,dois anos,73.35,
3134,0.0,dois anos,25.75,
3203,0.0,dois anos,52.55,
4169,0.0,dois anos,80.85,
5599,0.0,dois anos,19.85,

In [12]:
# mostrando os índices dos registros que não foram convertidos na coluna 'conta.cobranca.Total'
idx = dados_normalizados[dados_normalizados['conta.cobranca.Total'] == ' '].index
idx

Index([975, 1775, 1955, 2075, 2232, 2308, 2930, 3134, 3203, 4169, 5599], dtype='int64')

In [13]:
# corrigindo os valores da coluna 'conta.cobranca.Total' multiplicando por 24 os valores da mensalidade
dados_normalizados.loc[idx, "conta.cobranca.Total"] = dados_normalizados.loc[idx, "conta.cobranca.mensal"] * 24

In [14]:
# corrigindo os valores da coluna 'conta.cobranca.Total' atribuindo o valor 24 diretamente  
dados_normalizados.loc[idx, "cliente.tempo_servico"] = 24

In [15]:
# verificando se os valores foram corrigidos
dados_normalizados.loc[idx][['cliente.tempo_servico', 'conta.contrato', 'conta.cobranca.mensal', 'conta.cobranca.Total']]

,cliente.tempo_servico,conta.contrato,conta.cobranca.mensal,conta.cobranca.Total
975,24.0,dois anos,56.05,1345.2
1775,24.0,dois anos,20.00,480.0
1955,24.0,dois anos,61.90,1485.6
2075,24.0,dois anos,19.70,472.8
2232,24.0,dois anos,20.25,486.0
2308,24.0,dois anos,25.35,608.4
2930,24.0,dois anos,73.35,1760.4
3134,24.0,dois anos,25.75,618.0
3203,24.0,dois anos,52.55,1261.2
4169,24.0,dois anos,80.85,1940.4
5599,24.0,dois anos,19.85,476.4

In [16]:
# Convertendo novamente a coluna 'conta.cobranca.Total' para float64, agora sem erros
dados_normalizados['conta.cobranca.Total'] = dados_normalizados['conta.cobranca.Total'].astype('float64')
dados_normalizados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7344 entries, 0 to 7343
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id_cliente                     7344 non-null   object
 1   Churn                          7344 non-null   object
 2   cliente.genero                 7344 non-null   object
 3   cliente.idoso                  7344 non-null   int64
 4   cliente.parceiro               7344 non-null   object
 5   cliente.dependentes            7344 non-null   object
 6   cliente.tempo_servico          7336 non-null   float64
 7   telefone.servico_telefone      7344 non-null   object
 8   telefone.varias_linhas         7344 non-null   object
 9   internet.servico_internet      7344 non-null   object
 10  internet.seguranca_online      7344 non-null   object
 11  internet.backup_online         7344 non-null   object
 12  internet.protecao_dispositivo  7344 non-null   object
 13  internet.suporte_tecnico       7344 non-null   object
 14  internet.tv_streaming          7344 non-null   object
 15  internet.filmes_streaming      7344 non-null   object
 16  conta.contrato                 7312 non-null   object
 17  conta.faturamente_eletronico   7326 non-null   object
 18  conta.metodo_pagamento         7317 non-null   object
 19  conta.cobranca.mensal          7326 non-null   float64
 20  conta.cobranca.Total           7328 non-null   float64
dtypes: float64(3), int64(1), object(17)
memory usage: 1.2+ MB

In [17]:
# visualizando os valores únicos de cada coluna do DataFrame
for col in dados_normalizados.columns:
    print(f"Coluna: {col}")
    print(dados_normalizados[col].unique())
    print("-" * 30)
    
    """O metodo unique() do pandas é utilizado para obter os valores únicos presentes em uma série ou coluna de um DataFrame. Ele retorna um array numpy contendo todos os valores distintos encontrados na série, eliminando quaisquer duplicatas. Isso é útil para entender a diversidade dos dados em uma coluna específica e para identificar categorias ou valores distintos presentes nos dados."""

Coluna: id_cliente
['0002-ORFBO' '0003-MKNFE' '0004-TLHLJ' ... '9992-UJOEL' '9993-LHIEB'
 '9995-HOTOH']
------------------------------
Coluna: Churn
['nao' 'sim' '']
------------------------------
Coluna: cliente.genero
['feminino' 'masculino']
------------------------------
Coluna: cliente.idoso
[0 1]
------------------------------
Coluna: cliente.parceiro
['sim' 'nao']
------------------------------
Coluna: cliente.dependentes
['sim' 'nao']
------------------------------
Coluna: cliente.tempo_servico
[9.00e+00 4.00e+00 1.30e+01 3.00e+00 7.10e+01 6.30e+01 7.00e+00      nan
 5.40e+01 7.20e+01 5.00e+00 5.60e+01 3.40e+01 1.00e+00 4.50e+01 5.00e+01
 2.30e+01 5.50e+01 2.60e+01 6.90e+01 1.10e+01 3.70e+01 4.90e+01 6.60e+01
 6.70e+01 2.00e+01 4.30e+01 5.90e+01 1.20e+01 2.70e+01 2.00e+00 2.50e+01
 2.90e+01 1.40e+01 3.50e+01 6.40e+01 3.90e+01 4.00e+01 6.00e+00 3.00e+01
 7.00e+01 5.70e+01 5.80e+01 1.60e+01 3.20e+01 3.30e+01 1.00e+01 2.10e+01
 6.10e+01 1.50e+01 4.40e+01 2.20e+01 2.40e+01 1.90e+01 4.70e+01 6.20e+01
 4.60e+01 5.20e+01 8.00e+00 6.00e+01 4.80e+01 2.80e+01 6.50e+01 4.10e+01
 5.30e+01 6.80e+01 5.10e+01 3.10e+01 3.60e+01 1.70e+01 1.80e+01 3.80e+01
 4.20e+01 1.08e+03 1.00e+03 9.50e+02 2.54e+02 3.21e+02 6.50e+02 7.00e+02
 7.21e+02 5.55e+02 4.33e+02 5.12e+02]
------------------------------
Coluna: telefone.servico_telefone
['sim' 'nao']
------------------------------
Coluna: telefone.varias_linhas
['nao' 'sim' 'sem servico de telefone']
------------------------------
Coluna: internet.servico_internet
['DSL' 'fibra otica' 'nao']
------------------------------
Coluna: internet.seguranca_online
['nao' 'sim' 'sem servico de internet']
------------------------------
Coluna: internet.backup_online
['sim' 'nao' 'sem servico de internet']
------------------------------
Coluna: internet.protecao_dispositivo
['nao' 'sim' 'sem servico de internet']
------------------------------
Coluna: internet.suporte_tecnico
['sim' 'nao' 'sem servico de internet']
------------------------------
Coluna: internet.tv_streaming
['sim' 'nao' 'sem servico de internet']
------------------------------
Coluna: internet.filmes_streaming
['nao' 'sim' 'sem servico de internet']
------------------------------
Coluna: conta.contrato
[None 'mes a mes' 'dois anos' 'um ano']
------------------------------
Coluna: conta.faturamente_eletronico
[None 'nao' 'sim']
------------------------------
Coluna: conta.metodo_pagamento
[None 'cheque pelo correio' 'cheque eletronico'
 'cartao de credito (automatico)' 'transferencia bancaria (automatica)']
------------------------------
Coluna: conta.cobranca.mensal
[  nan 59.9  73.9  ... 91.75 68.8  67.85]
------------------------------
Coluna: conta.cobranca.Total
[    nan  542.4   280.85 ...  742.9  4627.65 3707.6 ]
------------------------------

In [18]:
# visualizando os registros com valores vazios na coluna 'Churn'
dados_normalizados.query('Churn == ""')


""""O metodo query() do pandas é utilizado para filtrar linhas de um DataFrame com base em uma expressão booleana. Ele permite que você escreva consultas de forma mais legível e concisa, utilizando uma sintaxe semelhante à SQL. A expressão dentro do query() deve ser uma string que representa a condição que as linhas devem satisfazer para serem incluídas no resultado."""

'"O metodo query() do pandas é utilizado para filtrar linhas de um DataFrame com base em uma expressão booleana. Ele permite que você escreva consultas de forma mais legível e concisa, utilizando uma sintaxe semelhante à SQL. A expressão dentro do query() deve ser uma string que representa a condição que as linhas devem satisfazer para serem incluídas no resultado.'

In [19]:
# Criando um novo DataFrame sem os registros com valores vazios na coluna 'Churn' e copiando os dados
dados_sem_vazios = dados_normalizados[dados_normalizados['Churn'] != ''].copy()
dados_sem_vazios

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,0002-ORFBO,nao,feminino,0,sim,sim,9.0,sim,nao,DSL,...,sim,nao,sim,sim,nao,None,None,None,NaN,NaN
1,0003-MKNFE,nao,masculino,0,nao,nao,9.0,sim,sim,DSL,...,nao,nao,nao,nao,sim,mes a mes,nao,cheque pelo correio,59.90,542.40
2,0004-TLHLJ,sim,masculino,0,nao,nao,4.0,sim,nao,fibra otica,...,nao,sim,nao,nao,nao,mes a mes,sim,cheque eletronico,73.90,280.85
3,0011-IGKFF,sim,masculino,1,sim,nao,13.0,sim,nao,fibra otica,...,sim,sim,nao,sim,sim,mes a mes,sim,cheque eletronico,98.00,1237.85
4,0013-EXCHZ,sim,feminino,1,sim,nao,3.0,sim,nao,fibra otica,...,nao,nao,sim,sim,nao,mes a mes,sim,cheque pelo correio,83.90,267.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7338,5792-JALQC,nao,feminino,1,nao,nao,52.0,sim,sim,DSL,...,nao,sim,nao,nao,nao,dois anos,nao,transferencia bancaria (automatica),59.85,3103.25
7339,5172-RKOCB,nao,masculino,0,sim,nao,72.0,sim,sim,fibra otica,...,sim,nao,sim,sim,sim,dois anos,sim,cartao de credito (automatico),108.95,7875.00
7340,1934-MKPXS,nao,masculino,0,sim,sim,33.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,um ano,nao,cartao de credito (automatico),20.10,620.55
7341,5959-BELXA,sim,masculino,1,nao,nao,32.0,sim,sim,fibra otica,...,nao,nao,nao,sim,sim,mes a mes,sim,cartao de credito (automatico),96.15,3019.25
7343,4452-QIIEB,nao,masculino,0,nao,nao,7.0,sim,nao,DSL,...,nao,nao,nao,nao,nao,mes a mes,nao,cheque pelo correio,43.90,278.40

In [20]:
# Verificando que há indexes faltando no novo DataFrame
dados_sem_vazios.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7118 entries, 0 to 7343
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id_cliente                     7118 non-null   object
 1   Churn                          7118 non-null   object
 2   cliente.genero                 7118 non-null   object
 3   cliente.idoso                  7118 non-null   int64
 4   cliente.parceiro               7118 non-null   object
 5   cliente.dependentes            7118 non-null   object
 6   cliente.tempo_servico          7110 non-null   float64
 7   telefone.servico_telefone      7118 non-null   object
 8   telefone.varias_linhas         7118 non-null   object
 9   internet.servico_internet      7118 non-null   object
 10  internet.seguranca_online      7118 non-null   object
 11  internet.backup_online         7118 non-null   object
 12  internet.protecao_dispositivo  7118 non-null   object
 13  internet.suporte_tecnico       7118 non-null   object
 14  internet.tv_streaming          7118 non-null   object
 15  internet.filmes_streaming      7118 non-null   object
 16  conta.contrato                 7086 non-null   object
 17  conta.faturamente_eletronico   7100 non-null   object
 18  conta.metodo_pagamento         7091 non-null   object
 19  conta.cobranca.mensal          7100 non-null   float64
 20  conta.cobranca.Total           7102 non-null   float64
dtypes: float64(3), int64(1), object(17)
memory usage: 1.2+ MB

In [21]:
# resetando os índices do DataFrame sem valores vazios
dados_sem_vazios.reset_index(drop=True, inplace=True)
dados_sem_vazios

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,0002-ORFBO,nao,feminino,0,sim,sim,9.0,sim,nao,DSL,...,sim,nao,sim,sim,nao,None,None,None,NaN,NaN
1,0003-MKNFE,nao,masculino,0,nao,nao,9.0,sim,sim,DSL,...,nao,nao,nao,nao,sim,mes a mes,nao,cheque pelo correio,59.90,542.40
2,0004-TLHLJ,sim,masculino,0,nao,nao,4.0,sim,nao,fibra otica,...,nao,sim,nao,nao,nao,mes a mes,sim,cheque eletronico,73.90,280.85
3,0011-IGKFF,sim,masculino,1,sim,nao,13.0,sim,nao,fibra otica,...,sim,sim,nao,sim,sim,mes a mes,sim,cheque eletronico,98.00,1237.85
4,0013-EXCHZ,sim,feminino,1,sim,nao,3.0,sim,nao,fibra otica,...,nao,nao,sim,sim,nao,mes a mes,sim,cheque pelo correio,83.90,267.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7113,5792-JALQC,nao,feminino,1,nao,nao,52.0,sim,sim,DSL,...,nao,sim,nao,nao,nao,dois anos,nao,transferencia bancaria (automatica),59.85,3103.25
7114,5172-RKOCB,nao,masculino,0,sim,nao,72.0,sim,sim,fibra otica,...,sim,nao,sim,sim,sim,dois anos,sim,cartao de credito (automatico),108.95,7875.00
7115,1934-MKPXS,nao,masculino,0,sim,sim,33.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,um ano,nao,cartao de credito (automatico),20.10,620.55
7116,5959-BELXA,sim,masculino,1,nao,nao,32.0,sim,sim,fibra otica,...,nao,nao,nao,sim,sim,mes a mes,sim,cartao de credito (automatico),96.15,3019.25
7117,4452-QIIEB,nao,masculino,0,nao,nao,7.0,sim,nao,DSL,...,nao,nao,nao,nao,nao,mes a mes,nao,cheque pelo correio,43.90,278.40

 ## Trabalhando com dados duplicados e nulos

Identificando e tratando dados duplicados

In [22]:
dados_sem_vazios.duplicated()

"""O metodo duplicated() do pandas é utilizado para identificar linhas duplicadas em um DataFrame. Ele retorna uma série booleana indicando se cada linha é uma duplicata de uma linha anterior. Isso é útil para detectar e remover registros duplicados em conjuntos de dados, garantindo a integridade e a qualidade dos dados para análise."""

'O metodo duplicated() do pandas é utilizado para identificar linhas duplicadas em um DataFrame. Ele retorna uma série booleana indicando se cada linha é uma duplicata de uma linha anterior. Isso é útil para detectar e remover registros duplicados em conjuntos de dados, garantindo a integridade e a qualidade dos dados para análise.'

In [23]:
# Contando o número de registros duplicados no DataFrame sem valores vazios
dados_sem_vazios.duplicated().sum()

np.int64(75)

In [24]:
# Verificando se os registros duplicados foram removidos e atribuindo o resultado a variável filtro_duplicados
filtro_duplicados = dados_sem_vazios.duplicated()
filtro_duplicados

0       False
1       False
2       False
3       False
4       False
        ...
7113     True
7114     True
7115     True
7116     True
7117     True
Length: 7118, dtype: bool

In [ ]:
# Visualizando os registros duplicados
dados_sem_vazios[filtro_duplicados]

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
7043,0675-NCDYU,nao,feminino,0,sim,sim,72.0,sim,sim,fibra otica,...,sim,sim,sim,sim,sim,dois anos,sim,cartao de credito (automatico),116.40,8543.25
7044,6754-LZUKA,nao,masculino,0,sim,nao,61.0,sim,sim,DSL,...,sim,sim,nao,sim,sim,dois anos,nao,transferencia bancaria (automatica),80.90,4932.50
7045,2192-CKRLV,nao,feminino,0,sim,nao,72.0,nao,sem servico de telefone,DSL,...,sim,sim,nao,nao,sim,dois anos,sim,cheque eletronico,49.20,3580.95
7046,9170-ARBTB,nao,feminino,0,sim,sim,52.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,um ano,nao,cartao de credito (automatico),19.60,1012.40
7047,0447-BEMNG,sim,feminino,0,sim,nao,48.0,nao,sem servico de telefone,DSL,...,nao,sim,nao,nao,sim,mes a mes,sim,transferencia bancaria (automatica),45.30,2145.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7113,5792-JALQC,nao,feminino,1,nao,nao,52.0,sim,sim,DSL,...,nao,sim,nao,nao,nao,dois anos,nao,transferencia bancaria (automatica),59.85,3103.25
7114,5172-RKOCB,nao,masculino,0,sim,nao,72.0,sim,sim,fibra otica,...,sim,nao,sim,sim,sim,dois anos,sim,cartao de credito (automatico),108.95,7875.00
7115,1934-MKPXS,nao,masculino,0,sim,sim,33.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,um ano,nao,cartao de credito (automatico),20.10,620.55
7116,5959-BELXA,sim,masculino,1,nao,nao,32.0,sim,sim,fibra otica,...,nao,nao,nao,sim,sim,mes a mes,sim,cartao de credito (automatico),96.15,3019.25
7117,4452-QIIEB,nao,masculino,0,nao,nao,7.0,sim,nao,DSL,...,nao,nao,nao,nao,nao,mes a mes,nao,cheque pelo correio,43.90,278.40

In [28]:
# Removendo os registros duplicados do DataFrame sem valores vazios
dados_sem_vazios.drop_duplicates(inplace=True)


"""O metodo drop_duplicates() do pandas é utilizado para remover linhas duplicadas de um DataFrame. Ele identifica e elimina registros que são idênticos em todas as colunas ou em colunas específicas, mantendo apenas a primeira ocorrência de cada conjunto de duplicatas. Isso é útil para garantir a integridade dos dados e evitar redundâncias em análises e operações subsequentes.

implace=True significa que a operação será realizada no próprio DataFrame, modificando-o diretamente, em vez de retornar uma nova cópia do DataFrame com as duplicatas removidas."""

'O metodo drop_duplicates() do pandas é utilizado para remover linhas duplicadas de um DataFrame. Ele identifica e elimina registros que são idênticos em todas as colunas ou em colunas específicas, mantendo apenas a primeira ocorrência de cada conjunto de duplicatas. Isso é útil para garantir a integridade dos dados e evitar redundâncias em análises e operações subsequentes.\n\nimplace=True significa que a operação será realizada no próprio DataFrame, modificando-o diretamente, em vez de retornar uma nova cópia do DataFrame com as duplicatas removidas.'

In [32]:
# Verificando o número de registros duplicados após a remoção
dados_sem_vazios.duplicated().sum()

np.int64(0)

Identificando e Substituindo dados nulos

In [ ]:
# Identificando e Substituindo dados nulos
dados_sem_vazios.isna()

"""O metodo isna() do pandas é utilizado para identificar valores nulos ou ausentes em um DataFrame ou Série. Ele retorna uma estrutura booleana do mesmo formato, onde cada elemento é True se o valor correspondente for nulo (NaN) e False caso contrário. Isso é útil para detectar e lidar com dados faltantes em conjuntos de dados, permitindo que os usuários tomem decisões informadas sobre como tratar esses valores em análises subsequentes."""

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7039,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7040,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7041,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7042,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
# Contando o número de valores nulos em cada coluna do DataFrame sem valores vazios
dados_sem_vazios.isna().sum()

id_cliente                        0
Churn                             0
cliente.genero                    0
cliente.idoso                     0
cliente.parceiro                  0
cliente.dependentes               0
cliente.tempo_servico             8
telefone.servico_telefone         0
telefone.varias_linhas            0
internet.servico_internet         0
internet.seguranca_online         0
internet.backup_online            0
internet.protecao_dispositivo     0
internet.suporte_tecnico          0
internet.tv_streaming             0
internet.filmes_streaming         0
conta.contrato                   31
conta.faturamente_eletronico     17
conta.metodo_pagamento           26
conta.cobranca.mensal            17
conta.cobranca.Total             15
dtype: int64

In [ ]:
# Contando o número total de valores nulos no DataFrame sem valores vazios  
dados_sem_vazios.isna().sum().sum()

np.int64(114)

In [ ]:
# Visualizando os registros com valores nulos
dados_sem_vazios[dados_sem_vazios.isna().any(axis=1)]

"""O metodo any(axis=1) é utilizado para verificar se há pelo menos um valor True em cada linha (quando axis=1) ou em cada coluna (quando axis=0) de um DataFrame ou Série. No contexto de dados nulos, ele pode ser usado para identificar linhas ou colunas que contêm valores nulos, retornando True para aquelas que possuem pelo menos um valor nulo e False para aquelas que não possuem nenhum valor nulo."""

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,0002-ORFBO,nao,feminino,0,sim,sim,9.0,sim,nao,DSL,...,sim,nao,sim,sim,nao,None,None,None,NaN,NaN
9,0016-QLJIS,nao,feminino,0,sim,sim,NaN,sim,sim,DSL,...,sim,sim,sim,sim,sim,dois anos,sim,cheque pelo correio,90.45,5957.90
176,0282-NVSJS,nao,feminino,1,sim,sim,NaN,nao,sem servico de telefone,DSL,...,nao,nao,sim,nao,nao,mes a mes,sim,cheque pelo correio,29.30,355.90
181,0295-QVKPB,nao,masculino,0,nao,nao,NaN,sim,nao,DSL,...,nao,sim,sim,sim,nao,mes a mes,sim,cartao de credito (automatico),63.95,318.10
437,0639-TSIQW,sim,feminino,0,nao,nao,67.0,sim,sim,fibra otica,...,sim,sim,nao,sim,nao,None,None,cartao de credito (automatico),NaN,6886.25
751,1095-WGNGG,nao,feminino,0,sim,nao,NaN,sim,sim,fibra otica,...,sim,nao,nao,sim,sim,dois anos,sim,transferencia bancaria (automatica),101.05,5971.25
963,1396-QWFBJ,sim,feminino,0,sim,sim,21.0,sim,nao,fibra otica,...,sim,nao,nao,nao,nao,None,sim,None,NaN,1565.70
1604,2333-KWEWW,nao,masculino,0,nao,nao,18.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,None,nao,None,20.05,NaN
1605,2335-GSODA,nao,masculino,0,nao,sim,23.0,nao,sem servico de telefone,DSL,...,nao,sim,sim,nao,nao,None,nao,None,NaN,NaN
1606,2338-BQEZT,nao,feminino,0,nao,nao,55.0,sim,nao,DSL,...,nao,nao,nao,nao,nao,None,sim,cartao de credito (automatico),NaN,NaN
1608,2344-JMOGN,sim,masculino,0,sim,nao,9.0,sim,nao,fibra otica,...,sim,sim,sim,sim,nao,mes a mes,None,cheque pelo correio,NaN,890.60
2036,2931-FSOHN,nao,masculino,1,nao,nao,13.0,sim,nao,DSL,...,sim,nao,nao,sim,nao,mes a mes,sim,None,59.90,788.35
2037,2931-SVLTV,nao,masculino,0,sim,sim,40.0,sim,sim,fibra otica,...,sim,nao,sim,sim,sim,None,None,None,NaN,NaN
2039,2931-XIQBR,nao,feminino,0,sim,sim,50.0,sim,nao,fibra otica,...,nao,sim,sim,sim,sim,None,None,cheque pelo correio,103.05,5153.50
3523,4994-OBRSZ,nao,masculino,0,nao,sim,NaN,sim,nao,DSL,...,sim,sim,sim,nao,sim,dois anos,nao,transferencia bancaria (automatica),76.10,1054.80
4712,6637-KYRCV,nao,feminino,0,sim,sim,5.0,nao,sem servico de telefone,DSL,...,sim,nao,nao,nao,nao,None,None,None,NaN,NaN
4716,6646-QVXLR,sim,masculino,1,sim,nao,62.0,sim,sim,fibra otica,...,sim,sim,nao,sim,sim,None,sim,cheque eletronico,NaN,NaN
4718,6647-ZEDXT,nao,feminino,0,nao,nao,30.0,sim,sim,fibra otica,...,sim,sim,sim,sim,sim,None,nao,None,110.45,3327.05
4721,6650-VJONK,nao,masculino,0,nao,nao,1.0,sim,nao,DSL,...,nao,nao,nao,nao,nao,None,sim,transferencia bancaria (automatica),NaN,NaN
4725,6653-CBBOM,sim,feminino,0,nao,nao,1.0,sim,nao,fibra otica,...,nao,nao,nao,nao,nao,None,sim,None,70.30,70.30
4728,6656-GULJQ,nao,masculino,0,sim,sim,72.0,sim,sim,DSL,...,nao,sim,sim,sim,sim,None,None,cartao de credito (automatico),83.55,NaN
4731,6661-HBGWL,sim,feminino,1,nao,nao,42.0,sim,sim,fibra otica,...,sim,sim,nao,sim,sim,None,sim,None,104.75,NaN
4733,6664-FPDAC,sim,feminino,1,nao,nao,56.0,sim,sim,fibra otica,...,sim,sim,sim,sim,sim,None,sim,cheque eletronico,NaN,NaN
4738,6680-NENYN,sim,feminino,0,nao,nao,43.0,sim,sim,fibra otica,...,sim,sim,nao,sim,sim,None,sim,None,104.60,4759.85
4740,6681-ZSEXG,nao,masculino,0,sim,nao,56.0,sim,sim,DSL,...,sim,sim,nao,nao,nao,dois anos,nao,None,59.50,3389.25
4745,6685-XSHHU,nao,masculino,0,sim,sim,60.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,dois anos,None,None,20.95,NaN
4749,6689-TCZHQ,sim,feminino,1,nao,nao,5.0,sim,nao,fibra otica,...,nao,nao,nao,nao,sim,mes a mes,None,None,78.95,378.40
4751,6691-CCIHA,nao,feminino,0,sim,nao,62.0,sim,sim,DSL,...,sim,nao,sim,sim,sim,None,sim,None,84.95,5150.55
4755,6693-FRIRW,nao,masculino,0,nao,nao,18.0,sim,nao,fibra otica,...,sim,sim,nao,sim,sim,None,nao,None,NaN,NaN
4762,6702-OHFWR,sim,masculino,1,nao,nao,1.0,nao,sem servico de telefone,DSL,...,sim,sim,nao,nao,sim,None,None,None,43.30,43.30
5273,7435-ZNUYY,nao,masculino,0,nao,nao,NaN,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,um ano,nao,cheque pelo correio,20.60,116.60
5276,7445-WMRBW,nao,feminino,0,nao,nao,NaN,sim,sim,DSL,...,sim,sim,sim,sim,nao,um ano,sim,transferencia bancaria (automatica),73.85,3581.40
5396,7606-BPHHN,nao,masculino,0,nao,nao,72.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,None,sim,cartao de credito (automatico),19.80,1468.75
5397,7607-QKKTJ,nao,masculino,0,sim,sim,45.0,sim,sim,fibra otica,...,sim,sim,nao,nao,sim,None,None,None,NaN,4368.85
5402,7611-YKYTC,nao,masculino,0,sim,sim,22.0,sim,nao,fibra otica,...,nao,nao,nao,nao,nao,None,nao,transferencia bancaria (automatica),NaN,NaN
5404,7614-QVWQL,sim,masculino,0,sim,sim,49.0,nao,sem servico de telefone,DSL,...,sim,nao,nao,sim,sim,None,None,None,NaN,NaN
5410,7622-FWGEW,nao,masculino,1,sim,nao,56.0,sim,nao,DSL,...,sim,sim,sim,sim,sim,None,sim,None,NaN,4824.45
5412,7623-HKYRK,nao,masculino,0,nao,sim,6.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,None,None,None,19.70,111.65
5415,7627-JKIAZ,sim,feminino,0,sim,nao,37.0,sim,sim,fibra otica,...,nao,sim,nao,nao,nao,mes a mes,sim,None,78.95,2839.65
6007,8480-PPONV,nao,masculino,0,sim,sim,62.0,sim,sim,fibra otica,...,sim,sim,sim,sim,sim,None,None,transferencia bancaria (automatica),NaN,7159.05
6134,8690-UPCZI,nao,masculino,0,sim,sim,NaN,sim,sim,DSL,...,nao,nao,sim,sim,nao,um ano,nao,transferencia bancaria (automatica),69.05,1958.45
6181,8748-HFWBO,nao,masculino,0,sim,sim,19.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,None,None,None,19.90,357.70
6652,9465-RWMXL,sim,masculino,0,sim,nao,32.0,sim,sim,fibra otica,...,nao,sim,nao,nao,nao,None,None,None,78.90,2447.95
6655,9470-RTWDV,nao,masculino,0,sim,sim,26.0,sim,sim,DSL,...,nao,sim,sim,sim,sim,None,None,None,82.00,2083.10
6656,9470-XCCEM,nao,masculino,0,sim,sim,35.0,sim,sim,fibra otica,...,sim,nao,nao,sim,nao,None,sim,None,89.65,3161.60

In [ ]:
# Criando um filtro para identificar os registros com valores nulos na coluna 'cliente.tempo_servico'
filtro = dados_sem_vazios['cliente.tempo_servico'].isna()

In [ ]:
# Visualizando os registros com valores nulos na coluna 'cliente.tempo_servico' 
dados_sem_vazios[filtro][['cliente.tempo_servico', 'conta.cobranca.mensal', 'conta.cobranca.Total']]

      cliente.tempo_servico  conta.cobranca.mensal  conta.cobranca.Total
9                       NaN                  90.45               5957.90
176                     NaN                  29.30                355.90
181                     NaN                  63.95                318.10
751                     NaN                 101.05               5971.25
3523                    NaN                  76.10               1054.80
5273                    NaN                  20.60                116.60
5276                    NaN                  73.85               3581.40
6134                    NaN                  69.05               1958.45

In [ ]:
# Substituindo os valores nulos na coluna 'cliente.tempo_servico' pela divisão arredondada para cima da coluna 'conta.cobranca.Total' pela coluna 'conta.cobranca.mensal'
dados_sem_vazios['cliente.tempo_servico'].fillna(
    np.ceil(dados_sem_vazios['conta.cobranca.Total'] / dados_sem_vazios['conta.cobranca.mensal']), inplace=True
)

"""O metodo fillna() do pandas é utilizado para preencher valores nulos (NaN) em um DataFrame ou Série com um valor específico ou utilizando uma estratégia de preenchimento, como o valor anterior ou posterior. Isso é útil para lidar com dados faltantes, permitindo que os usuários substituam esses valores nulos por informações relevantes, facilitando análises e operações subsequentes. O parâmetro inplace=True indica que a operação será realizada no próprio DataFrame, modificando-o diretamente, em vez de retornar uma nova cópia do DataFrame com os valores nulos preenchidos."""

In [ ]:
# Visualizando os registros com valores nulos na coluna 'cliente.tempo_servico' após a substituição
dados_sem_vazios[filtro][['cliente.tempo_servico', 'conta.cobranca.mensal', 'conta.cobranca.Total']]

      cliente.tempo_servico  conta.cobranca.mensal  conta.cobranca.Total
9                      66.0                  90.45               5957.90
176                    13.0                  29.30                355.90
181                     5.0                  63.95                318.10
751                    60.0                 101.05               5971.25
3523                   14.0                  76.10               1054.80
5273                    6.0                  20.60                116.60
5276                   49.0                  73.85               3581.40
6134                   29.0                  69.05               1958.45

In [ ]:
# Visualizando o número de valores nulos em cada coluna do DataFrame sem valores vazios após a substituição
dados_sem_vazios.isna().sum()


"""Existem alguns métodos da biblioteca Pandas que nos auxiliam a identificar quais são dados nulos em nosso DataFrame, como:

isnull(): retorna um DataFrame de valores booleanos, no qual True indica o valor nulo e False indica o valor válido.
notnull(): retorna um DataFrame de valores booleanos, no qual True indica o valor válido e False indica o valor nulo.
isna(): retorna um DataFrame de valores booleanos, com True indicando o valor nulo e False o valor válido (a mesma funcionalidade do método isnull()).
notna(): retorna um DataFrame de valores booleanos, em que True indica o valor válido e False indica o valor nulo (a mesma funcionalidade do método notnull()).

Além disso, podemos utilizar o método fillna() para substituir os valores nulos por um valor específico ou por uma estratégia de preenchimento, como o valor anterior ou posterior. Isso é útil para lidar com dados faltantes e garantir a integridade dos dados para análises subsequentes.
# Identificando e Substituindo dados nulos"""

id_cliente                        0
Churn                             0
cliente.genero                    0
cliente.idoso                     0
cliente.parceiro                  0
cliente.dependentes               0
cliente.tempo_servico             0
telefone.servico_telefone         0
telefone.varias_linhas            0
internet.servico_internet         0
internet.seguranca_online         0
internet.backup_online            0
internet.protecao_dispositivo     0
internet.suporte_tecnico          0
internet.tv_streaming             0
internet.filmes_streaming         0
conta.contrato                   31
conta.faturamente_eletronico     17
conta.metodo_pagamento           26
conta.cobranca.mensal            17
conta.cobranca.Total             15
dtype: int64

Retirando o restante dos dados nulos do DataFrame

In [54]:
# Visualizando a distribuição de valores da coluna 'conta.contrato'
dados_normalizados['conta.contrato'].value_counts()

conta.contrato
mes a mes    4039
dois anos    1755
um ano       1518
Name: count, dtype: int64

In [55]:
# Atribuindo o valor das colunas a serem removidas a variável colunas_dropar
colunas_dropar = ['conta.contrato', 'conta.faturamente_eletronico', 'conta.metodo_pagamento']

In [56]:
# Vizualizando os dados nulos nas colunas a serem removidas e somando a quantidade de registros com valores nulos   
dados_sem_vazios[colunas_dropar].isna().any(axis=1).sum()

"""O metodo any(axis=1) é utilizado para verificar se há pelo menos um valor True em cada linha (quando axis=1) ou em cada coluna (quando axis=0) de um DataFrame ou Série. No contexto de dados nulos, ele pode ser usado para identificar linhas ou colunas que contêm valores nulos, retornando True para aquelas que possuem pelo menos um valor nulo e False para aquelas que não possuem nenhum valor nulo.

O metodo isna() é utilizado para verificar se todos os valores em um DataFrame ou Série são iguais. Ele retorna True se todos os valores forem iguais e False se houver pelo menos um valor diferente."""

'O metodo any(axis=1) é utilizado para verificar se há pelo menos um valor True em cada linha (quando axis=1) ou em cada coluna (quando axis=0) de um DataFrame ou Série. No contexto de dados nulos, ele pode ser usado para identificar linhas ou colunas que contêm valores nulos, retornando True para aquelas que possuem pelo menos um valor nulo e False para aquelas que não possuem nenhum valor nulo.\n\nO metodo isna() é utilizado para verificar se todos os valores em um DataFrame ou Série são iguais. Ele retorna True se todos os valores forem iguais e False se houver pelo menos um valor diferente.'

In [64]:
# Retirando o restante dos dados nulos do DataFrame e atribuindo a variável dados_sem_nulos e copiando os dados
df_dados_sem_nulos = dados_normalizados.dropna(subset=colunas_dropar).copy()
df_dados_sem_nulos.head()

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
1,0003-MKNFE,nao,masculino,0,nao,nao,9.0,sim,sim,DSL,...,nao,nao,nao,nao,sim,mes a mes,nao,cheque pelo correio,59.9,542.40
2,0004-TLHLJ,sim,masculino,0,nao,nao,4.0,sim,nao,fibra otica,...,nao,sim,nao,nao,nao,mes a mes,sim,cheque eletronico,73.9,280.85
3,0011-IGKFF,sim,masculino,1,sim,nao,13.0,sim,nao,fibra otica,...,sim,sim,nao,sim,sim,mes a mes,sim,cheque eletronico,98.0,1237.85
4,0013-EXCHZ,sim,feminino,1,sim,nao,3.0,sim,nao,fibra otica,...,nao,nao,sim,sim,nao,mes a mes,sim,cheque pelo correio,83.9,267.40
5,0013-MHZWF,nao,feminino,0,nao,sim,9.0,sim,nao,DSL,...,nao,nao,sim,sim,sim,mes a mes,sim,cartao de credito (automatico),69.4,571.45

In [65]:
# Resetando o index do DataFrame sem nulos
df_dados_sem_nulos.reset_index(drop=True, inplace=True)
df_dados_sem_nulos.head()

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,0003-MKNFE,nao,masculino,0,nao,nao,9.0,sim,sim,DSL,...,nao,nao,nao,nao,sim,mes a mes,nao,cheque pelo correio,59.9,542.40
1,0004-TLHLJ,sim,masculino,0,nao,nao,4.0,sim,nao,fibra otica,...,nao,sim,nao,nao,nao,mes a mes,sim,cheque eletronico,73.9,280.85
2,0011-IGKFF,sim,masculino,1,sim,nao,13.0,sim,nao,fibra otica,...,sim,sim,nao,sim,sim,mes a mes,sim,cheque eletronico,98.0,1237.85
3,0013-EXCHZ,sim,feminino,1,sim,nao,3.0,sim,nao,fibra otica,...,nao,nao,sim,sim,nao,mes a mes,sim,cheque pelo correio,83.9,267.40
4,0013-MHZWF,nao,feminino,0,nao,sim,9.0,sim,nao,DSL,...,nao,nao,sim,sim,sim,mes a mes,sim,cartao de credito (automatico),69.4,571.45

In [ ]:
# Visualizando a contagem de valores nulos no DataFrame sem nulos
df_dados_sem_nulos.isna().sum()

id_cliente                       0
Churn                            0
cliente.genero                   0
cliente.idoso                    0
cliente.parceiro                 0
cliente.dependentes              0
cliente.tempo_servico            8
telefone.servico_telefone        0
telefone.varias_linhas           0
internet.servico_internet        0
internet.seguranca_online        0
internet.backup_online           0
internet.protecao_dispositivo    0
internet.suporte_tecnico         0
internet.tv_streaming            0
internet.filmes_streaming        0
conta.contrato                   0
conta.faturamente_eletronico     0
conta.metodo_pagamento           0
conta.cobranca.mensal            0
conta.cobranca.Total             0
dtype: int64