In [21]:
import pandas as pd

url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv'

dados = pd.read_csv(url, sep=';')

dados.head(10)

  Nome,Idade,Notas,Aprovado
0           Ary,20,7.5,True
1             Ana,18,,False
2        Cátia,27,2.5,False
3        Denis,18,5.0,False
4         Beto,21,10.0,True
5           Bruna,23,,False
6          Dara,21,7.0,True
7        Carlos,19,6.0,True
8        Alice,35,5.6,False
9           Vitor,28,,False

In [22]:
dados.tail(10)

   Nome,Idade,Notas,Aprovado
8         Alice,35,5.6,False
9            Vitor,28,,False
10          Daniel,21,,False
11         Igor,24,4.5,False
12     Sthefanie,26,9.5,True
13         Mirla,25,9.0,True
14           Paulo,37,,False
15        Mylena,29,7.0,True
16           Lucas,33,,False
17         Nadia,34,8.0,True

In [23]:
type(dados) #mostra o tipo do dataframe
dados.dtypes #mostra o tipo de cada coluna do dataframe
dados.shape #mostra o numero de linhas e colunas do dataframe
dados.columns #mostra o nome das colunas do dataframe
dados.info() #mostra o tipo de cada coluna do dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Nome,Idade,Notas,Aprovado  18 non-null     object
dtypes: object(1)
memory usage: 276.0+ bytes

In [24]:
dados.dtypes
dados.info() #mostra o tipo do dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Nome,Idade,Notas,Aprovado  18 non-null     object
dtypes: object(1)
memory usage: 276.0+ bytes

In [25]:
dados.columns #mostra o nome das colunas do dataframe

Index(['Nome,Idade,Notas,Aprovado'], dtype='object')

In [26]:
dados.describe() #mostra o resumo dos dados do dataframe

       Nome,Idade,Notas,Aprovado
count                         18
unique                        18
top              Ary,20,7.5,True
freq                           1

1. Verifique se a base de dados possui dados nulos e, caso tenha, realize o tratamento desses dados nulos da forma que achar mais coerente com a situação.

In [27]:
dados.isnull() #mostra a quantidade de valores nulos em cada coluna do dataframe

    Nome,Idade,Notas,Aprovado
0                       False
1                       False
2                       False
3                       False
4                       False
5                       False
6                       False
7                       False
8                       False
9                       False
10                      False
11                      False
12                      False
13                      False
14                      False
15                      False
16                      False
17                      False

In [33]:
dados.isnull().sum() #mostra a soma dos valores nulos em cada coluna do dataframe

Nome,Idade,Notas,Aprovado    0
dtype: int64

2) Os alunos "Alice" e "Carlos", não fazem mais parte da turma. Sendo assim, remova-os da base de dados.

In [ ]:
# separando as colunas do dataframe
# criando um dataframe com as colunas separadas
dados_temp = dados['Nome,Idade,Notas,Aprovado'].str.split(',', expand=True)
dados_temp.columns = ['Nome', 'Idade', 'Notas', 'Aprovado']
alunos_a_remover = dados_temp.query('Nome == "Alice" | Nome == "Carlos"').index # seleciona os indices dos alunos Alice e Carlos

In [31]:
# removendo as linhas referentes aos alunos "Alice" e "Carlos"
dados.drop(alunos_a_remover, axis=0, inplace=True)

In [ ]:
# filtrando os alunos aprovados
selecao = dados_temp['Aprovado'] == 'True'
dados[selecao]

C:\Users\eleil\AppData\Local\Temp\ipykernel_16912\1346435211.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  dados[selecao]

   Nome,Idade,Notas,Aprovado
0            Ary,20,7.5,True
4          Beto,21,10.0,True
6           Dara,21,7.0,True
12     Sthefanie,26,9.5,True
13         Mirla,25,9.0,True
15        Mylena,29,7.0,True
17         Nadia,34,8.0,True

In [ ]:
# armazenando os dados dos alunos aprovados em um novo dataframe
alunos_aprovados = dados[selecao]

C:\Users\eleil\AppData\Local\Temp\ipykernel_16912\3457713215.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  alunos_aprovados = dados[selecao]

In [ ]:
# salvando os dados dos alunos aprovados em um arquivo csv
alunos_aprovados.to_csv('alunos_aprovados.csv', index=False)

In [ ]:
# substituindo a nota 7.0 pela nota 8.0 no dataframe dos alunos aprovados
alunos_aprovados = alunos_aprovados.replace(7.0, 8.0)

   Nome,Idade,Notas,Aprovado
0            Ary,20,7.5,True
4          Beto,21,10.0,True
6           Dara,21,7.0,True
12     Sthefanie,26,9.5,True
13         Mirla,25,9.0,True
15        Mylena,29,7.0,True
17         Nadia,34,8.0,True

In [ ]:
# substituindo a nota 7.0 pela nota 8.0 no dataframe dos alunos aprovados
alunos_aprovados = alunos_aprovados.replace(7.0, 8.0)
alunos_aprovados

   Nome,Idade,Notas,Aprovado
0            Ary,20,7.5,True
4          Beto,21,10.0,True
6           Dara,21,7.0,True
12     Sthefanie,26,9.5,True
13         Mirla,25,9.0,True
15        Mylena,29,7.0,True
17         Nadia,34,8.0,True