TRABALHANDO COM ARQUIVO CSV

Um supermercado que está planejando uma liquidação de fim de ano, eles querem oferecer uma assinatura que dá 20% de desconto em todas as compras.

E o time de marketing desse supermercado entende que a melhor maneira de diminuir custos com essa campanha é analisar os dados de compras dos clientes e entender quais teriam mais chances de aderir a essa assinatura e oferecer diretamente a essas pessoas.

In [ ]:
# Importando a biblioteca pandas
import pandas as pd
# Definindo o caminho do arquivo CSV
url = 'C:\\Users\\eleil\\OneDrive\\Documents\\GitHub\\Estudo-e-Projetos-Alura\\Python para Data Sciense\\Pandas\\Trabalhando com diferentes arquivos\\dados\\superstore_data.csv'
# Lendo o arquivo CSV e armazenando em um DataFrame
dados_mercado = pd.read_csv(url)
# Exibindo as primeiras 5 linhas do DataFrame   
dados_mercado.head(5)

"""head(): Exibe as primeiras n linhas do DataFrame. O padrão é 5."""

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [ ]:
# Lendo um arquivo CSV com separador ponto e vírgula
url_2 = "C:\\Users\\eleil\\OneDrive\\Documents\\GitHub\\Estudo-e-Projetos-Alura\\Python para Data Sciense\\Pandas\\Trabalhando com diferentes arquivos\\dados\\superstore_data_ponto_virgula.csv"
# Lendo o arquivo CSV com separador ponto e vírgula
dados_ponto_virgula = pd.read_csv(url_2, sep=';')
# Exibindo as primeiras 5 linhas do DataFrame
dados_ponto_virgula.head(5)

'''pd.read_csv() possui diversos parâmetros que permitem customizar a leitura do arquivo CSV, como por exemplo: 
- sep: Define o separador utilizado no arquivo (padrão é vírgula).
- nrows: Define o número de linhas a serem lidas do arquivo.
- usecols: Permite selecionar colunas específicas para serem lidas do arquivo.
Esses parâmetros ajudam a adaptar a leitura do arquivo CSV conforme as necessidades específicas da análise de dados.'''

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [ ]:
# Lendo apenas as primeiras 5 linhas do arquivo CSV
dados_primeias_linhas = pd.read_csv(url, nrows=5)
dados_primeias_linhas

"""nrows: Define o número de linhas a serem lidas do arquivo."""

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [ ]:
# Lendo apenas colunas específicas do arquivo CSV
dados_selecao = pd.read_csv(url, usecols=['Id', 'Year_Birth', 'Income'])
dados_selecao.head(5)

"""usecols: Permite selecionar colunas específicas para serem lidas do arquivo."""

      Id  Year_Birth   Income
0   1826        1970  84835.0
1      1        1961  57091.0
2  10476        1958  67267.0
3   1386        1967  32474.0
4   5371        1989  21474.0

In [ ]:
# Lendo apenas colunas específicas do arquivo CSV usando índices das colunas
dados_selecao = pd.read_csv(url, usecols=[0, 1, 4])
dados_selecao.head(5)

      Id  Year_Birth   Income
0   1826        1970  84835.0
1      1        1961  57091.0
2  10476        1958  67267.0
3   1386        1967  32474.0
4   5371        1989  21474.0

In [ ]:
# Salvando o DataFrame em um novo arquivo CSV
dados_selecao.to_csv('clientes_mercado.csv', index=False)

"""index=False: Evita que o índice do DataFrame seja salvo como uma coluna no arquivo CSV."""

In [18]:
# Lendo o arquivo CSV salvo anteriormente
clientes_mercado = pd.read_csv('clientes_mercado.csv')
clientes_mercado

         Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

In [ ]:
"""Parametros adicionais do to_csv():   
index=False: Evita que o índice do DataFrame seja salvo como uma coluna no arquivo CSV.
sep=';': Define o separador utilizado no arquivo CSV (padrão é vírgula).
header=False: Não inclui os nomes das colunas no arquivo CSV.
columns=['Id', 'Year_Birth']: Especifica quais colunas do DataFrame devem ser salvas no arquivo CSV.    
encoding='utf-8': Define a codificação do arquivo CSV (padrão é 'utf-8').   
compression='gzip': Salva o arquivo CSV em formato comprimido (gzip).
quotechar='"': Define o caractere utilizado para envolver valores de texto no arquivo CSV (padrão é aspas duplas).
date_format='%Y-%m-%d': Define o formato de data para colunas do tipo datetime no arquivo CSV.  
float_format='%.2f': Define o formato de números de ponto flutuante no arquivo CSV (neste caso, com duas casas decimais).
chunksize=1000: Salva o DataFrame em partes (chunks) de tamanho especificado, útil para grandes conjuntos de dados.
skiprows=3: indica que as três primeiras linhas do arquivo devem ser ignoradas, pois não contêm dados relevantes.
skipfooter = 9: indica que as nove últimas linhas do arquivo devem ser ignoradas, pois não contêm dados relevantes.
engine='python': o motor usado para ler o arquivo é o Python. Isso é necessário quando se usa o parâmetro skipfooter, pois o motor padrão não suporta essa opção.
usecols = 'A:C': especifica que apenas as colunas A, B e C do arquivo devem ser lidas.  
dtype={'Id': int, 'Year_Birth': int, 'Income': float}: define os tipos de dados para as colunas especificadas, garantindo que sejam lidas corretamente.
engine='python': o motor usado para ler o arquivo é o Python. Isso é necessário quando se usa o parâmetro skipfooter, pois o motor padrão não suporta essa opção.
na_values=['NA', '?']: especifica valores adicionais que devem ser tratados como valores ausentes (NaN) no DataFrame.
iterator=True: retorna um iterador que permite ler o arquivo em pedaços (chunks) de tamanho especificado.
na_filter=False: desativa a detecção automática de valores ausentes (NaN) no arquivo.
decimal=',': define o caractere usado como separador decimal no arquivo (neste caso, vírgula).
Esses parâmetros adicionais permitem maior controle sobre como o DataFrame é salvo em um arquivo CSV, adaptando-se às necessidades específicas do usuário.  """

TRABALHANDO COM PLANILHAS

Analisar esses dados com o objetivo de entender os impactos ambientais gerados pelos países e pensar em questões de sustentabilidade

In [15]:
# Instalando a biblioteca openpyxl necessária para ler arquivos Excel
%pip install openpyxl
# Importando a biblioteca pandas
import pandas as pd
# Definindo o caminho do arquivo Excel
url = r"C:\Users\eleil\OneDrive\Documents\GitHub\Estudo-e-Projetos-Alura\Python para Data Sciense\Pandas\Trabalhando com diferentes arquivos\dados\emissoes_CO2.xlsx"
# Lendo o arquivo Excel e armazenando em um DataFrame
dados_co2 = pd.read_excel(url)
# Exibindo as primeiras 5 linhas do DataFrame
dados_co2.head(5)

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\eleil\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\eleil\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\eleil\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Listando os nomes das planilhas no arquivo Excel
pd.ExcelFile(url).sheet_names

"""Class ExcelFile: Permite acessar informações sobre o arquivo Excel, como os nomes das planilhas."""

['emissoes_C02', 'emissoes_percapita', 'fontes']

In [25]:
# Lendo uma planilha específica do arquivo Excel e armazenando em um DataFrame   
percapta = pd.read_excel(url, sheet_name='emissoes_percapita')
percapta

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Óleo,Gás,Cimento,Queima,Outro
0,Afeganistão,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,4749682.0,1908857.0,1610910.0,940144.0,198416.0,51579.0,39776.0
63100,Global,WLD,2018,4792753.0,1919213.0,1596350.0,979965.0,204225.0,53634.0,39366.0
63101,Global,WLD,2019,4775633.0,1896468.0,1589920.0,984878.0,208309.0,56569.0,39490.0
63102,Global,WLD,2020,4497423.0,1807760.0,1427353.0,963695.0,208844.0,51981.0,37789.0
63103,Global,WLD,2021,4693699.0,1893923.0,1496614.0,1001585.0,211472.0,52663.0,37443.0

In [24]:
# Lendo outra planilha específica do arquivo Excel e armazenando em um DataFrame
fontes = pd.read_excel(url, sheet_name='fontes')
fontes

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
1,Afeganistão,AFG,1751,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
2,Afeganistão,AFG,1752,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
3,Afeganistão,AFG,1753,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
4,Afeganistão,AFG,1754,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
...,...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63100,Global,WLD,2018,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63101,Global,WLD,2019,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63102,Global,WLD,2020,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63103,Global,WLD,2021,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."

In [23]:
# Lendo outra planilha específica do arquivo Excel e armazenando em um DataFrame e escolhendo colunas específicas
intervaalo = pd.read_excel(url, sheet_name='emissoes_C02', usecols='A:D')
intervaalo

              País ISO 3166-1 alpha-3   Ano         Total
0      Afeganistão                AFG  1750  0.000000e+00
1      Afeganistão                AFG  1751  0.000000e+00
2      Afeganistão                AFG  1752  0.000000e+00
3      Afeganistão                AFG  1753  0.000000e+00
4      Afeganistão                AFG  1754  0.000000e+00
...            ...                ...   ...           ...
63099       Global                WLD  2017  3.609674e+10
63100       Global                WLD  2018  3.682651e+10
63101       Global                WLD  2019  3.708256e+10
63102       Global                WLD  2020  3.526409e+10
63103       Global                WLD  2021  3.712385e+10

[63104 rows x 4 columns]

In [ ]:
# Lendo outra planilha específica do arquivo Excel e armazenando em um DataFrame, escolhendo colunas específicas e limitando o número de linhas lidas
intervaalo_2 = pd.read_excel(url, sheet_name='emissoes_C02', usecols='A:D', nrows=10)
intervaalo_2

          País ISO 3166-1 alpha-3   Ano  Total
0  Afeganistão                AFG  1750      0
1  Afeganistão                AFG  1751      0
2  Afeganistão                AFG  1752      0
3  Afeganistão                AFG  1753      0
4  Afeganistão                AFG  1754      0
5  Afeganistão                AFG  1755      0
6  Afeganistão                AFG  1756      0
7  Afeganistão                AFG  1757      0
8  Afeganistão                AFG  1758      0
9  Afeganistão                AFG  1759      0

In [ ]:
"""Parametros adicionais do read_excel():
- usecols: Permite selecionar colunas específicas para serem lidas do arquivo Excel.
- nrows: Define o número de linhas a serem lidas do arquivo Excel.
sheet_name: Especifica qual planilha do arquivo Excel deve ser lida.
Class ExcelFile: Permite acessar informações sobre o arquivo Excel, como os nomes das planilhas.    
header=0: Indica a linha que deve ser usada como cabeçalho do DataFrame.
names=None: Permite definir nomes personalizados para as colunas do DataFrame.
index_col=None: Permite definir uma ou mais colunas como índice do DataFrame.
dtype=None: Permite especificar os tipos de dados para as colunas do DataFrame.
parse_dates=False: Indica se as colunas devem ser analisadas como datas.
engine=None: Permite escolher o motor utilizado para ler o arquivo Excel (padrão é 'openpyxl' para arquivos .xlsx).
converters=None: Permite definir funções de conversão para colunas específicas.
keep_default_na=True: Indica se os valores padrão de NA devem ser mantidos.
na_values=None: Permite definir valores adicionais que devem ser considerados como NA.
na_filter=True: Indica se deve ser feita a filtragem de valores NA.
verbose=False: Indica se deve ser exibida informação detalhada durante a leitura do arquivo.
comment=None: Permite definir um caractere que indica o início de um comentário em uma linha.
skiprows=None: Permite pular um número específico de linhas no início do arquivo.
These parameters help to customize the reading of the Excel file according to the specific needs of data analysis.
"""

In [27]:
# Salvando o DataFrame em um novo arquivo Excel
percapta.to_excel('co2_percapta.xlsx', index=False)

In [ ]:
# Lendo o arquivo Excel salvo anteriormente
pd.read_excel('co2_percapta.xlsx')

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Óleo,Gás,Cimento,Queima,Outro
0,Afeganistão,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,4749682.0,1908857.0,1610910.0,940144.0,198416.0,51579.0,39776.0
63100,Global,WLD,2018,4792753.0,1919213.0,1596350.0,979965.0,204225.0,53634.0,39366.0
63101,Global,WLD,2019,4775633.0,1896468.0,1589920.0,984878.0,208309.0,56569.0,39490.0
63102,Global,WLD,2020,4497423.0,1807760.0,1427353.0,963695.0,208844.0,51981.0,37789.0
63103,Global,WLD,2021,4693699.0,1893923.0,1496614.0,1001585.0,211472.0,52663.0,37443.0

TRABALHANDO COM ARQUIVOS DIRETO DO GOOGLE PLANILHAS

In [ ]:
https://docs.google.com/spreadsheets/d/1tji1nDQY8Y-akXaz8dfcCgzrfYfRy6Rr/edit?usp=sharing&ouid=110151314417719987423&rtpof=true&sd=true

In [ ]:
# Lendo um arquivo CSV diretamente de uma planilha do Google Sheets usando o id da planilha
sheet_id = '1tji1nDQY8Y-akXaz8dfcCgzrfYfRy6Rr'
# Construindo a URL para acessar o CSV da planilha
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'
# Lendo o arquivo CSV da planilha do Google Sheets
dados_co2_sheets =pd.read_csv(url)
dados_co2_sheets.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Lendo uma planilha específica do google planilhas pelo id da planilha e armazenando em um DataFrame
sheet_id = '1tji1nDQY8Y-akXaz8dfcCgzrfYfRy6Rr'
# Lendo a pagina 'emissoes_percapita' da planilha do Google Sheets
shest_name = 'emissoes_percapita'
# Construindo a URL para acessar o CSV da planilha específica
url_percapita = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={shest_name}'
# Lendo o arquivo CSV da planilha específica do Google Sheets
percapita_sheets = pd.read_csv(url_percapita)
percapita_sheets.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Óleo,Gás,Cimento,Queima,Outro
0,Afeganistão,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
# Lendo uma planilha específica do google planilhas pelo id da planilha e armazenando em um DataFrame
sheet_id = '1tji1nDQY8Y-akXaz8dfcCgzrfYfRy6Rr'
# Lendo a pagina 'fontes' da planilha do Google Sheets
shest_name = 'fontes'
# Construindo a URL para acessar o CSV da planilha específica
url_fontes = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={shest_name}'
# Lendo o arquivo CSV da planilha específica do Google Sheets
fontes_sheets = pd.read_csv(url_fontes)
fontes_sheets.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
1,Afeganistão,AFG,1751,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
2,Afeganistão,AFG,1752,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
3,Afeganistão,AFG,1753,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
4,Afeganistão,AFG,1754,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]

In [ ]:
# Lendo uma planilha específica do google planilhas pelo id da planilha e armazenando em um DataFrame
sheet_id = '1tji1nDQY8Y-akXaz8dfcCgzrfYfRy6Rr'
# Lendo a pagina 'emissoes_ CO2' da planilha do Google Sheets
sheet_name = 'emissoes_CO2'
# Construindo a URL para acessar o CSV da planilha específica
url_emissoes_CO2 = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={shest_name}'
# Lendo o arquivo CSV da planilha específica do Google Sheets
emissoes_CO2 = pd.read_csv(url_emissoes_CO2)
emissoes_CO2.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
""""Parametros adicionais do read_csv() ao ler do Google Sheets:
- sep: Define o separador utilizado no arquivo CSV (padrão é vírgula
- header=0: Indica a linha que deve ser usada como cabeçalho do DataFrame.
gviz: Indica que o formato de saída é do Google Visualization API, necessário para acessar o CSV corretamente.  
tq?tqx=out:csv&sheet: Parâmetros adicionais para a consulta, onde 'out:csv' especifica que a saída deve ser em formato CSV e 'sheet' indica a planilha específica a ser acessada.
"""