MANIPULANDO E TRATANDO OS DADOS

In [ ]:
# Importando o Pandas
import pandas as pd
# Carregando o arquivo JSON em um DataFrame
# Normalizando os dados JSON aninhados
dados = pd.json_normalize(pd.read_json('C:\\Users\\eleil\\OneDrive\\Documents\\GitHub\\Estudo-e-Projetos-Alura\\Python para Data Sciense\\Pandas\\Transformação e manipulação de dados\\dados_hospedagem.json').to_dict('records'))
dados.head()

"""O metodo pd.json_normalize() do pandas é utilizado para transformar dados JSON aninhados em um DataFrame plano. No exemplo acima, estamos lendo um arquivo JSON chamado 'dados_hospedagem.json' e convertendo-o em um DataFrame utilizando pd.read_json(). Em seguida, o método to_dict('records') é chamado para converter o DataFrame em uma lista de dicionários, onde cada dicionário representa uma linha do DataFrame. Finalmente, pd.json_normalize() é aplicado para "normalizar" os dados JSON aninhados, criando colunas separadas para cada campo aninhado e resultando em um DataFrame mais fácil de manipular e analisar.

O metodo to_dict('records') é utilizado para converter um DataFrame em uma lista de dicionários, onde cada dicionário representa uma linha do DataFrame. No exemplo acima, estamos lendo um arquivo JSON chamado 'dados_hospedagem.json' e convertendo-o em um DataFrame utilizando pd.read_json(). Em seguida, o método to_dict('records') é chamado para transformar o DataFrame em uma lista de dicionários, facilitando a manipulação dos dados JSON aninhados. Cada dicionário na lista contém os pares chave-valor correspondentes às colunas e valores do DataFrame original."""

,info_moveis.avaliacao_geral,info_moveis.experiencia_local,info_moveis.max_hospedes,info_moveis.descricao_local,info_moveis.descricao_vizinhanca,info_moveis.quantidade_banheiros,info_moveis.quantidade_quartos,info_moveis.quantidade_camas,info_moveis.modelo_cama,info_moveis.comodidades,info_moveis.taxa_deposito,info_moveis.taxa_limpeza,info_moveis.preco
0,10.0,--,1,[This clean and comfortable one bedroom sits r...,[Lower Queen Anne is near the Seattle Center (...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Real Bed, Futon, Futon, Pull-out Sofa, Real B...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...","[$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...","[$110.00, $45.00, $55.00, $52.00, $85.00, $50...."
1,10.0,--,10,[Welcome to the heart of the 'Ballard Brewery ...,"[--, Capital Hill is the heart of Seattle, bor...","[2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]","[3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]","[5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$500.00, $300.00, $0, $300.00, $300.00, $360....","[$125.00, $100.00, $85.00, $110.00, $110.00, $...","[$350.00, $300.00, $425.00, $300.00, $285.00, ..."
2,10.0,--,11,[New modern house built in 2013. Spectacular ...,[Upper Queen Anne is a charming neighborhood f...,[4],[5],[7],[Real Bed],"[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00]",[$300.00],[$975.00]
3,10.0,--,12,[Our NW style home is 3200+ sq ft with 3 level...,[The Views from our top floor! Wallingford ha...,"[3, 3, 3, 3, 3, 3, 3, 3]","[6, 6, 5, 5, 5, 5, 4, 4]","[6, 6, 7, 8, 7, 7, 6, 6]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$500.00, $500.00, $500.00, $500.00, $500.00, ...","[$225.00, $300.00, $250.00, $250.00, $250.00, ...","[$490.00, $550.00, $350.00, $350.00, $350.00, ..."
4,10.0,--,14,"[Perfect for groups. 2 bedrooms, full bathroom...",[Safeway grocery store within walking distance...,"[2, 3]","[2, 6]","[3, 9]","[Real Bed, Real Bed]","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$300.00, $2,000.00]","[$40.00, $150.00]","[$200.00, $545.00]"

In [ ]:
# Listando as colunas do DataFrame
colunas = list(dados.columns)
colunas

['info_moveis.avaliacao_geral',
 'info_moveis.experiencia_local',
 'info_moveis.max_hospedes',
 'info_moveis.descricao_local',
 'info_moveis.descricao_vizinhanca',
 'info_moveis.quantidade_banheiros',
 'info_moveis.quantidade_quartos',
 'info_moveis.quantidade_camas',
 'info_moveis.modelo_cama',
 'info_moveis.comodidades',
 'info_moveis.taxa_deposito',
 'info_moveis.taxa_limpeza',
 'info_moveis.preco']

In [ ]:
# Explodindo as colunas que contêm listas em múltiplas linhas
dados = dados.explode(colunas[3:])
dados

"""O metodo explode() do pandas é utilizado para transformar colunas que contêm listas em múltiplas linhas, onde cada elemento da lista se torna uma linha separada. No exemplo acima, estamos aplicando o método explode() ao DataFrame dados, especificando as colunas a partir do índice 3 até o final da lista de colunas (colunas[3:]). Isso significa que todas as colunas a partir da quarta coluna serão "explodidas", criando novas linhas para cada elemento presente nas listas dessas colunas. O resultado é um DataFrame onde cada elemento das listas é representado em uma linha separada, facilitando a análise e manipulação dos dados."""

,info_moveis.avaliacao_geral,info_moveis.experiencia_local,info_moveis.max_hospedes,info_moveis.descricao_local,info_moveis.descricao_vizinhanca,info_moveis.quantidade_banheiros,info_moveis.quantidade_quartos,info_moveis.quantidade_camas,info_moveis.modelo_cama,info_moveis.comodidades,info_moveis.taxa_deposito,info_moveis.taxa_limpeza,info_moveis.preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
0,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
0,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
0,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
0,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,nan,--,8,Beautiful craftsman home in the historic Wedgw...,--,3,4,5,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$178.00,$299.00
68,nan,--,8,Located in a very easily accessible area of Se...,"Quiet, dead end street near I-5. The proximity...",2,4,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",$0,$99.00,$199.00
68,nan,--,8,This home is fully furnished and available wee...,--,1,3,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",$0,$0,$400.00
69,nan,--,9,This business-themed modern home features: *H...,Your hosts made Madison Valley their home when...,2,3,6,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$150.00,$250.00
69,nan,--,9,This welcoming home is in the quiet residentia...,"Despite the quiet, leafy streets of this resid...",1,4,6,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$500.00,$0,$350.00

In [19]:
# Reconfigurando o índice do DataFrame após a explosão
dados.reset_index(inplace=True, drop=True)

"""O metodo reset_index() do pandas é utilizado para redefinir o índice de um DataFrame. No exemplo acima, estamos aplicando reset_index() ao DataFrame dados após a operação de explosão realizada anteriormente. O parâmetro drop=True é utilizado para descartar o índice antigo, enquanto inplace=True indica que a modificação deve ser feita diretamente no DataFrame original, sem a necessidade de criar uma cópia. Como resultado, o DataFrame dados terá um novo índice sequencial, começando do zero, facilitando a manipulação e análise dos dados após a explosão das colunas."""

'O metodo reset_index() do pandas é utilizado para redefinir o índice de um DataFrame. No exemplo acima, estamos aplicando reset_index() ao DataFrame dados após a operação de explosão realizada anteriormente. O parâmetro drop=True é utilizado para descartar o índice antigo, enquanto inplace=True indica que a modificação deve ser feita diretamente no DataFrame original, sem a necessidade de criar uma cópia. Como resultado, o DataFrame dados terá um novo índice sequencial, começando do zero, facilitando a manipulação e análise dos dados após a explosão das colunas.'

In [20]:
dados

,info_moveis.avaliacao_geral,info_moveis.experiencia_local,info_moveis.max_hospedes,info_moveis.descricao_local,info_moveis.descricao_vizinhanca,info_moveis.quantidade_banheiros,info_moveis.quantidade_quartos,info_moveis.quantidade_camas,info_moveis.modelo_cama,info_moveis.comodidades,info_moveis.taxa_deposito,info_moveis.taxa_limpeza,info_moveis.preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3813,nan,--,8,Beautiful craftsman home in the historic Wedgw...,--,3,4,5,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$178.00,$299.00
3814,nan,--,8,Located in a very easily accessible area of Se...,"Quiet, dead end street near I-5. The proximity...",2,4,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",$0,$99.00,$199.00
3815,nan,--,8,This home is fully furnished and available wee...,--,1,3,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",$0,$0,$400.00
3816,nan,--,9,This business-themed modern home features: *H...,Your hosts made Madison Valley their home when...,2,3,6,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$150.00,$250.00
3817,nan,--,9,This welcoming home is in the quiet residentia...,"Despite the quiet, leafy streets of this resid...",1,4,6,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$500.00,$0,$350.00

In [ ]:
# Exibindo informações resumidas sobre o DataFrame
dados.info()

"""Dados object: O tipo de dado 'object' no pandas é utilizado para representar colunas que contêm dados heterogêneos, como strings, listas ou outros tipos de objetos. No exemplo acima, a coluna 'dados' do DataFrame contém dados do tipo 'object', indicando que os valores nessa coluna podem variar em termos de tipo e estrutura. Isso é comum em colunas que armazenam informações complexas ou não estruturadas, como listas de itens ou textos variados."""

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   info_moveis.avaliacao_geral       3818 non-null   object
 1   info_moveis.experiencia_local     3818 non-null   object
 2   info_moveis.max_hospedes          3818 non-null   object
 3   info_moveis.descricao_local       3818 non-null   object
 4   info_moveis.descricao_vizinhanca  3818 non-null   object
 5   info_moveis.quantidade_banheiros  3818 non-null   object
 6   info_moveis.quantidade_quartos    3818 non-null   object
 7   info_moveis.quantidade_camas      3818 non-null   object
 8   info_moveis.modelo_cama           3818 non-null   object
 9   info_moveis.comodidades           3818 non-null   object
 10  info_moveis.taxa_deposito         3818 non-null   object
 11  info_moveis.taxa_limpeza          3818 non-null   object
 12  info_moveis.preco                 3818 non-null   object
dtypes: object(13)
memory usage: 387.9+ KB

In [22]:
import numpy as np
# Substituindo valores ausentes (NaN) por um valor específico em colunas num

In [ ]:
# Transformando a coluna 'info_moveis.max_hospedes' para o tipo inteiro
dados['info_moveis.max_hospedes']=dados['info_moveis.max_hospedes'].astype(np.int64)

"""O metodo astype() do pandas é utilizado para converter o tipo de dado de uma coluna em um DataFrame. No exemplo acima, estamos aplicando astype(np.int64) à coluna 'info_moveis.max_hospedes' do DataFrame dados, convertendo seus valores para o tipo inteiro de 64 bits (np.int64). Isso é útil quando queremos garantir que os dados sejam tratados como inteiros, permitindo operações matemáticas e análises específicas relacionadas a esse tipo de dado."""

In [ ]:
# Exibindo informações resumidas sobre o DataFrame
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   info_moveis.avaliacao_geral       3818 non-null   object
 1   info_moveis.experiencia_local     3818 non-null   object
 2   info_moveis.max_hospedes          3818 non-null   int64
 3   info_moveis.descricao_local       3818 non-null   object
 4   info_moveis.descricao_vizinhanca  3818 non-null   object
 5   info_moveis.quantidade_banheiros  3818 non-null   object
 6   info_moveis.quantidade_quartos    3818 non-null   object
 7   info_moveis.quantidade_camas      3818 non-null   object
 8   info_moveis.modelo_cama           3818 non-null   object
 9   info_moveis.comodidades           3818 non-null   object
 10  info_moveis.taxa_deposito         3818 non-null   object
 11  info_moveis.taxa_limpeza          3818 non-null   object
 12  info_moveis.preco                 3818 non-null   object
dtypes: int64(1), object(12)
memory usage: 387.9+ KB

In [30]:
# Definindo uma lista de colunas numéricas
colunas_numericas = ['info_moveis.quantidade_quartos', 'info_moveis.quantidade_banheiros', 'info_moveis.quantidade_camas']

In [ ]:
# Convertendo as colunas numéricas para o tipo inteiro  
dados[colunas_numericas] = dados[colunas_numericas].astype(np.int64)

"""O metodo astype() do pandas é utilizado para converter o tipo de dado de uma coluna em um DataFrame. No exemplo acima, estamos aplicando astype(np.int64) à coluna 'info_moveis.max_hospedes' do DataFrame dados, convertendo seus valores para o tipo inteiro de 64 bits (np.int64). Isso é útil quando queremos garantir que os dados sejam tratados como inteiros, permitindo operações matemáticas e análises específicas relacionadas a esse tipo de dado."""

In [ ]:
# Convertendo a coluna 'info_moveis.avaliacao_geral' para o tipo float
dados['info_moveis.avaliacao_geral'] = dados['info_moveis.avaliacao_geral'].astype(np.float64)

"""O metodo astype() do pandas é utilizado para converter o tipo de dado de uma coluna em um DataFrame. No exemplo acima, estamos aplicando astype(np.int64) à coluna 'info_moveis.max_hospedes' do DataFrame dados, convertendo seus valores para o tipo inteiro de 64 bits (np.int64). Isso é útil quando queremos garantir que os dados sejam tratados como inteiros, permitindo operações matemáticas e análises específicas relacionadas a esse tipo de dado."""

In [33]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   info_moveis.avaliacao_geral       3162 non-null   float64
 1   info_moveis.experiencia_local     3818 non-null   object
 2   info_moveis.max_hospedes          3818 non-null   int64
 3   info_moveis.descricao_local       3818 non-null   object
 4   info_moveis.descricao_vizinhanca  3818 non-null   object
 5   info_moveis.quantidade_banheiros  3818 non-null   int64
 6   info_moveis.quantidade_quartos    3818 non-null   int64
 7   info_moveis.quantidade_camas      3818 non-null   int64
 8   info_moveis.modelo_cama           3818 non-null   object
 9   info_moveis.comodidades           3818 non-null   object
 10  info_moveis.taxa_deposito         3818 non-null   object
 11  info_moveis.taxa_limpeza          3818 non-null   object
 12  info_moveis.preco                 3818 non-null   object
dtypes: float64(1), int64(4), object(8)
memory usage: 387.9+ KB

In [ ]:
# Convertendo a coluna 'info_moveis.preco' para o tipo float
dados['info_moveis.preco'] = dados['info_moveis.preco'].astype(np.float64)

ValueError: could not convert string to float: '$110.00'

In [ ]:
# Substituindo um valor específico ($ e ,) por um valor vazio e convertendo para float
# Convertendo a coluna 'info_moveis.preco' para o tipo float
dados['info_moveis.preco'] = dados['info_moveis.preco'].apply(lambda x: x.replace('$', '').replace(',','').strip()).astype(np.float64)

"""O metodo astype() do pandas é utilizado para converter o tipo de dado de uma coluna em um DataFrame. No exemplo acima, estamos aplicando astype(np.int64) à coluna 'info_moveis.max_hospedes' do DataFrame dados, convertendo seus valores para o tipo inteiro de 64 bits (np.int64). Isso é útil quando queremos garantir que os dados sejam tratados como inteiros, permitindo operações matemáticas e análises específicas relacionadas a esse tipo de dado.

O metodo replace() é utilizado para substituir ocorrências de um valor específico por outro valor em uma string. No exemplo acima, estamos aplicando replace('$', '') à coluna 'info_moveis.preco' do DataFrame dados, removendo o símbolo de dólar ('$') dos valores dessa coluna. Em seguida, também utilizamos replace(',', '') para remover as vírgulas que podem estar presentes nos valores numéricos formatados como strings. Finalmente, o método strip() é chamado para remover quaisquer espaços em branco extras no início ou no final da string. Após essas substituições, os valores são convertidos para o tipo float utilizando astype(np.float64), permitindo que sejam tratados como números decimais para análises e cálculos posteriores."""

In [42]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   info_moveis.avaliacao_geral       3162 non-null   float64
 1   info_moveis.experiencia_local     3818 non-null   object
 2   info_moveis.max_hospedes          3818 non-null   int64
 3   info_moveis.descricao_local       3818 non-null   object
 4   info_moveis.descricao_vizinhanca  3818 non-null   object
 5   info_moveis.quantidade_banheiros  3818 non-null   int64
 6   info_moveis.quantidade_quartos    3818 non-null   int64
 7   info_moveis.quantidade_camas      3818 non-null   int64
 8   info_moveis.modelo_cama           3818 non-null   object
 9   info_moveis.comodidades           3818 non-null   object
 10  info_moveis.taxa_deposito         3818 non-null   object
 11  info_moveis.taxa_limpeza          3818 non-null   object
 12  info_moveis.preco                 3818 non-null   float64
dtypes: float64(2), int64(4), object(7)
memory usage: 387.9+ KB

In [47]:
# Substituindo um valor específico ($ e ,) por um valor vazio e convertendo para float
# Convertendo a coluna 'info_moveis.preco' para o tipo float 
# Atribuindo a conersão a uma nova variável
dados[['info_moveis.taxa_deposito', 'info_moveis.taxa_limpeza']] = dados[['info_moveis.taxa_deposito', 'info_moveis.taxa_limpeza']].applymap(lambda x: x.replace('$', '').replace(',','').strip()).astype(np.float64)

C:\Users\eleil\AppData\Local\Temp\ipykernel_31708\1657461863.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  dados[['info_moveis.taxa_deposito', 'info_moveis.taxa_limpeza']] = dados[['info_moveis.taxa_deposito', 'info_moveis.taxa_limpeza']].applymap(lambda x: x.replace('$', '').replace(',','').strip()).astype(np.float64)

In [48]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   info_moveis.avaliacao_geral       3162 non-null   float64
 1   info_moveis.experiencia_local     3818 non-null   object
 2   info_moveis.max_hospedes          3818 non-null   int64
 3   info_moveis.descricao_local       3818 non-null   object
 4   info_moveis.descricao_vizinhanca  3818 non-null   object
 5   info_moveis.quantidade_banheiros  3818 non-null   int64
 6   info_moveis.quantidade_quartos    3818 non-null   int64
 7   info_moveis.quantidade_camas      3818 non-null   int64
 8   info_moveis.modelo_cama           3818 non-null   object
 9   info_moveis.comodidades           3818 non-null   object
 10  info_moveis.taxa_deposito         3818 non-null   float64
 11  info_moveis.taxa_limpeza          3818 non-null   float64
 12  info_moveis.preco                 3818 non-null   float64
dtypes: float64(4), int64(4), object(5)
memory usage: 387.9+ KB