MANIPULANDO E TRATANDO OS DADOS

Conhecendo os dados

In [15]:
# Importando o Pandas
import pandas as pd
# Carregando o arquivo JSON em um DataFrame
# Normalizando os dados JSON aninhados
dados = pd.json_normalize(pd.read_json('C:\\Users\\eleil\\OneDrive\\Documents\\GitHub\\Estudo-e-Projetos-Alura\\Python para Data Sciense\\Pandas\\Transformação e manipulação de dados\\dados_hospedagem.json').to_dict('records'))
dados.head()

"""O metodo pd.json_normalize() do pandas é utilizado para transformar dados JSON aninhados em um DataFrame plano. No exemplo acima, estamos lendo um arquivo JSON chamado 'dados_hospedagem.json' e convertendo-o em um DataFrame utilizando pd.read_json(). Em seguida, o método to_dict('records') é chamado para converter o DataFrame em uma lista de dicionários, onde cada dicionário representa uma linha do DataFrame. Finalmente, pd.json_normalize() é aplicado para "normalizar" os dados JSON aninhados, criando colunas separadas para cada campo aninhado e resultando em um DataFrame mais fácil de manipular e analisar.

O metodo to_dict('records') é utilizado para converter um DataFrame em uma lista de dicionários, onde cada dicionário representa uma linha do DataFrame. No exemplo acima, estamos lendo um arquivo JSON chamado 'dados_hospedagem.json' e convertendo-o em um DataFrame utilizando pd.read_json(). Em seguida, o método to_dict('records') é chamado para transformar o DataFrame em uma lista de dicionários, facilitando a manipulação dos dados JSON aninhados. Cada dicionário na lista contém os pares chave-valor correspondentes às colunas e valores do DataFrame original."""

'O metodo pd.json_normalize() do pandas é utilizado para transformar dados JSON aninhados em um DataFrame plano. No exemplo acima, estamos lendo um arquivo JSON chamado \'dados_hospedagem.json\' e convertendo-o em um DataFrame utilizando pd.read_json(). Em seguida, o método to_dict(\'records\') é chamado para converter o DataFrame em uma lista de dicionários, onde cada dicionário representa uma linha do DataFrame. Finalmente, pd.json_normalize() é aplicado para "normalizar" os dados JSON aninhados, criando colunas separadas para cada campo aninhado e resultando em um DataFrame mais fácil de manipular e analisar.\n\nO metodo to_dict(\'records\') é utilizado para converter um DataFrame em uma lista de dicionários, onde cada dicionário representa uma linha do DataFrame. No exemplo acima, estamos lendo um arquivo JSON chamado \'dados_hospedagem.json\' e convertendo-o em um DataFrame utilizando pd.read_json(). Em seguida, o método to_dict(\'records\') é chamado para transformar o DataFrame em uma lista de dicionários, facilitando a manipulação dos dados JSON aninhados. Cada dicionário na lista contém os pares chave-valor correspondentes às colunas e valores do DataFrame original.'

In [16]:
# Listando as colunas do DataFrame
colunas = list(dados.columns)
colunas

['info_moveis.avaliacao_geral',
 'info_moveis.experiencia_local',
 'info_moveis.max_hospedes',
 'info_moveis.descricao_local',
 'info_moveis.descricao_vizinhanca',
 'info_moveis.quantidade_banheiros',
 'info_moveis.quantidade_quartos',
 'info_moveis.quantidade_camas',
 'info_moveis.modelo_cama',
 'info_moveis.comodidades',
 'info_moveis.taxa_deposito',
 'info_moveis.taxa_limpeza',
 'info_moveis.preco']

In [17]:
# Explodindo as colunas que contêm listas em múltiplas linhas
dados = dados.explode(colunas[3:])
dados

"""O metodo explode() do pandas é utilizado para transformar colunas que contêm listas em múltiplas linhas, onde cada elemento da lista se torna uma linha separada. No exemplo acima, estamos aplicando o método explode() ao DataFrame dados, especificando as colunas a partir do índice 3 até o final da lista de colunas (colunas[3:]). Isso significa que todas as colunas a partir da quarta coluna serão "explodidas", criando novas linhas para cada elemento presente nas listas dessas colunas. O resultado é um DataFrame onde cada elemento das listas é representado em uma linha separada, facilitando a análise e manipulação dos dados."""

'O metodo explode() do pandas é utilizado para transformar colunas que contêm listas em múltiplas linhas, onde cada elemento da lista se torna uma linha separada. No exemplo acima, estamos aplicando o método explode() ao DataFrame dados, especificando as colunas a partir do índice 3 até o final da lista de colunas (colunas[3:]). Isso significa que todas as colunas a partir da quarta coluna serão "explodidas", criando novas linhas para cada elemento presente nas listas dessas colunas. O resultado é um DataFrame onde cada elemento das listas é representado em uma linha separada, facilitando a análise e manipulação dos dados.'

In [18]:
# Reconfigurando o índice do DataFrame após a explosão
dados.reset_index(inplace=True, drop=True)

"""O metodo reset_index() do pandas é utilizado para redefinir o índice de um DataFrame. No exemplo acima, estamos aplicando reset_index() ao DataFrame dados após a operação de explosão realizada anteriormente. O parâmetro drop=True é utilizado para descartar o índice antigo, enquanto inplace=True indica que a modificação deve ser feita diretamente no DataFrame original, sem a necessidade de criar uma cópia. Como resultado, o DataFrame dados terá um novo índice sequencial, começando do zero, facilitando a manipulação e análise dos dados após a explosão das colunas."""

'O metodo reset_index() do pandas é utilizado para redefinir o índice de um DataFrame. No exemplo acima, estamos aplicando reset_index() ao DataFrame dados após a operação de explosão realizada anteriormente. O parâmetro drop=True é utilizado para descartar o índice antigo, enquanto inplace=True indica que a modificação deve ser feita diretamente no DataFrame original, sem a necessidade de criar uma cópia. Como resultado, o DataFrame dados terá um novo índice sequencial, começando do zero, facilitando a manipulação e análise dos dados após a explosão das colunas.'

In [19]:
dados

,info_moveis.avaliacao_geral,info_moveis.experiencia_local,info_moveis.max_hospedes,info_moveis.descricao_local,info_moveis.descricao_vizinhanca,info_moveis.quantidade_banheiros,info_moveis.quantidade_quartos,info_moveis.quantidade_camas,info_moveis.modelo_cama,info_moveis.comodidades,info_moveis.taxa_deposito,info_moveis.taxa_limpeza,info_moveis.preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3813,nan,--,8,Beautiful craftsman home in the historic Wedgw...,--,3,4,5,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$178.00,$299.00
3814,nan,--,8,Located in a very easily accessible area of Se...,"Quiet, dead end street near I-5. The proximity...",2,4,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",$0,$99.00,$199.00
3815,nan,--,8,This home is fully furnished and available wee...,--,1,3,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",$0,$0,$400.00
3816,nan,--,9,This business-themed modern home features: *H...,Your hosts made Madison Valley their home when...,2,3,6,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$150.00,$250.00
3817,nan,--,9,This welcoming home is in the quiet residentia...,"Despite the quiet, leafy streets of this resid...",1,4,6,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$500.00,$0,$350.00

In [20]:
# Exibindo informações resumidas sobre o DataFrame
dados.info()

"""Dados object: O tipo de dado 'object' no pandas é utilizado para representar colunas que contêm dados heterogêneos, como strings, listas ou outros tipos de objetos. No exemplo acima, a coluna 'dados' do DataFrame contém dados do tipo 'object', indicando que os valores nessa coluna podem variar em termos de tipo e estrutura. Isso é comum em colunas que armazenam informações complexas ou não estruturadas, como listas de itens ou textos variados."""

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   info_moveis.avaliacao_geral       3818 non-null   object
 1   info_moveis.experiencia_local     3818 non-null   object
 2   info_moveis.max_hospedes          3818 non-null   object
 3   info_moveis.descricao_local       3818 non-null   object
 4   info_moveis.descricao_vizinhanca  3818 non-null   object
 5   info_moveis.quantidade_banheiros  3818 non-null   object
 6   info_moveis.quantidade_quartos    3818 non-null   object
 7   info_moveis.quantidade_camas      3818 non-null   object
 8   info_moveis.modelo_cama           3818 non-null   object
 9   info_moveis.comodidades           3818 non-null   object
 10  info_moveis.taxa_deposito         3818 non-null   object
 11  info_moveis.taxa_limpeza          3818 non-null   object
 12  info_moveis.preco                 3818 non-null   object
dtypes: object(13)
memory usage: 387.9+ KB

"Dados object: O tipo de dado 'object' no pandas é utilizado para representar colunas que contêm dados heterogêneos, como strings, listas ou outros tipos de objetos. No exemplo acima, a coluna 'dados' do DataFrame contém dados do tipo 'object', indicando que os valores nessa coluna podem variar em termos de tipo e estrutura. Isso é comum em colunas que armazenam informações complexas ou não estruturadas, como listas de itens ou textos variados."

Tratando dados numéricos

In [21]:
import numpy as np
# Substituindo valores ausentes (NaN) por um valor específico em colunas num

In [22]:
# Transformando a coluna 'info_moveis.max_hospedes' para o tipo inteiro
dados['info_moveis.max_hospedes']=dados['info_moveis.max_hospedes'].astype(np.int64)

"""O metodo astype() do pandas é utilizado para converter o tipo de dado de uma coluna em um DataFrame. No exemplo acima, estamos aplicando astype(np.int64) à coluna 'info_moveis.max_hospedes' do DataFrame dados, convertendo seus valores para o tipo inteiro de 64 bits (np.int64). Isso é útil quando queremos garantir que os dados sejam tratados como inteiros, permitindo operações matemáticas e análises específicas relacionadas a esse tipo de dado."""

"O metodo astype() do pandas é utilizado para converter o tipo de dado de uma coluna em um DataFrame. No exemplo acima, estamos aplicando astype(np.int64) à coluna 'info_moveis.max_hospedes' do DataFrame dados, convertendo seus valores para o tipo inteiro de 64 bits (np.int64). Isso é útil quando queremos garantir que os dados sejam tratados como inteiros, permitindo operações matemáticas e análises específicas relacionadas a esse tipo de dado."

In [23]:
# Exibindo informações resumidas sobre o DataFrame
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   info_moveis.avaliacao_geral       3818 non-null   object
 1   info_moveis.experiencia_local     3818 non-null   object
 2   info_moveis.max_hospedes          3818 non-null   int64
 3   info_moveis.descricao_local       3818 non-null   object
 4   info_moveis.descricao_vizinhanca  3818 non-null   object
 5   info_moveis.quantidade_banheiros  3818 non-null   object
 6   info_moveis.quantidade_quartos    3818 non-null   object
 7   info_moveis.quantidade_camas      3818 non-null   object
 8   info_moveis.modelo_cama           3818 non-null   object
 9   info_moveis.comodidades           3818 non-null   object
 10  info_moveis.taxa_deposito         3818 non-null   object
 11  info_moveis.taxa_limpeza          3818 non-null   object
 12  info_moveis.preco                 3818 non-null   object
dtypes: int64(1), object(12)
memory usage: 387.9+ KB

In [24]:
# Definindo uma lista de colunas numéricas
colunas_numericas = ['info_moveis.quantidade_quartos', 'info_moveis.quantidade_banheiros', 'info_moveis.quantidade_camas']

In [25]:
# Convertendo as colunas numéricas para o tipo inteiro  
dados[colunas_numericas] = dados[colunas_numericas].astype(np.int64)

"""O metodo astype() do pandas é utilizado para converter o tipo de dado de uma coluna em um DataFrame. No exemplo acima, estamos aplicando astype(np.int64) à coluna 'info_moveis.max_hospedes' do DataFrame dados, convertendo seus valores para o tipo inteiro de 64 bits (np.int64). Isso é útil quando queremos garantir que os dados sejam tratados como inteiros, permitindo operações matemáticas e análises específicas relacionadas a esse tipo de dado."""

"O metodo astype() do pandas é utilizado para converter o tipo de dado de uma coluna em um DataFrame. No exemplo acima, estamos aplicando astype(np.int64) à coluna 'info_moveis.max_hospedes' do DataFrame dados, convertendo seus valores para o tipo inteiro de 64 bits (np.int64). Isso é útil quando queremos garantir que os dados sejam tratados como inteiros, permitindo operações matemáticas e análises específicas relacionadas a esse tipo de dado."

In [26]:
# Convertendo a coluna 'info_moveis.avaliacao_geral' para o tipo float
dados['info_moveis.avaliacao_geral'] = dados['info_moveis.avaliacao_geral'].astype(np.float64)

"""O metodo astype() do pandas é utilizado para converter o tipo de dado de uma coluna em um DataFrame. No exemplo acima, estamos aplicando astype(np.int64) à coluna 'info_moveis.max_hospedes' do DataFrame dados, convertendo seus valores para o tipo inteiro de 64 bits (np.int64). Isso é útil quando queremos garantir que os dados sejam tratados como inteiros, permitindo operações matemáticas e análises específicas relacionadas a esse tipo de dado."""

"O metodo astype() do pandas é utilizado para converter o tipo de dado de uma coluna em um DataFrame. No exemplo acima, estamos aplicando astype(np.int64) à coluna 'info_moveis.max_hospedes' do DataFrame dados, convertendo seus valores para o tipo inteiro de 64 bits (np.int64). Isso é útil quando queremos garantir que os dados sejam tratados como inteiros, permitindo operações matemáticas e análises específicas relacionadas a esse tipo de dado."

In [27]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   info_moveis.avaliacao_geral       3162 non-null   float64
 1   info_moveis.experiencia_local     3818 non-null   object
 2   info_moveis.max_hospedes          3818 non-null   int64
 3   info_moveis.descricao_local       3818 non-null   object
 4   info_moveis.descricao_vizinhanca  3818 non-null   object
 5   info_moveis.quantidade_banheiros  3818 non-null   int64
 6   info_moveis.quantidade_quartos    3818 non-null   int64
 7   info_moveis.quantidade_camas      3818 non-null   int64
 8   info_moveis.modelo_cama           3818 non-null   object
 9   info_moveis.comodidades           3818 non-null   object
 10  info_moveis.taxa_deposito         3818 non-null   object
 11  info_moveis.taxa_limpeza          3818 non-null   object
 12  info_moveis.preco                 3818 non-null   object
dtypes: float64(1), int64(4), object(8)
memory usage: 387.9+ KB

In [28]:
# Convertendo a coluna 'info_moveis.preco' para o tipo float
dados['info_moveis.preco'] = dados['info_moveis.preco'].astype(np.float64)

ValueError: could not convert string to float: '$110.00'

In [ ]:
# Substituindo um valor específico ($ e ,) por um valor vazio e convertendo para float
# Convertendo a coluna 'info_moveis.preco' para o tipo float
dados['info_moveis.preco'] = dados['info_moveis.preco'].apply(lambda x: x.replace('$', '').replace(',','').strip()).astype(np.float64)

"""O metodo astype() do pandas é utilizado para converter o tipo de dado de uma coluna em um DataFrame. No exemplo acima, estamos aplicando astype(np.int64) à coluna 'info_moveis.max_hospedes' do DataFrame dados, convertendo seus valores para o tipo inteiro de 64 bits (np.int64). Isso é útil quando queremos garantir que os dados sejam tratados como inteiros, permitindo operações matemáticas e análises específicas relacionadas a esse tipo de dado.

O metodo replace() é utilizado para substituir ocorrências de um valor específico por outro valor em uma string. No exemplo acima, estamos aplicando replace('$', '') à coluna 'info_moveis.preco' do DataFrame dados, removendo o símbolo de dólar ('$') dos valores dessa coluna. Em seguida, também utilizamos replace(',', '') para remover as vírgulas que podem estar presentes nos valores numéricos formatados como strings. Finalmente, o método strip() é chamado para remover quaisquer espaços em branco extras no início ou no final da string. Após essas substituições, os valores são convertidos para o tipo float utilizando astype(np.float64), permitindo que sejam tratados como números decimais para análises e cálculos posteriores."""

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   info_moveis.avaliacao_geral       3162 non-null   float64
 1   info_moveis.experiencia_local     3818 non-null   object
 2   info_moveis.max_hospedes          3818 non-null   int64
 3   info_moveis.descricao_local       3818 non-null   object
 4   info_moveis.descricao_vizinhanca  3818 non-null   object
 5   info_moveis.quantidade_banheiros  3818 non-null   int64
 6   info_moveis.quantidade_quartos    3818 non-null   int64
 7   info_moveis.quantidade_camas      3818 non-null   int64
 8   info_moveis.modelo_cama           3818 non-null   object
 9   info_moveis.comodidades           3818 non-null   object
 10  info_moveis.taxa_deposito         3818 non-null   object
 11  info_moveis.taxa_limpeza          3818 non-null   object
 12  info_moveis.preco                 3818 non-null   float64
dtypes: float64(2), int64(4), object(7)
memory usage: 387.9+ KB

In [ ]:
# Substituindo um valor específico ($ e ,) por um valor vazio e convertendo para float
# Convertendo a coluna 'info_moveis.preco' para o tipo float 
# Atribuindo a conersão a uma nova variável
dados[['info_moveis.taxa_deposito', 'info_moveis.taxa_limpeza']] = dados[['info_moveis.taxa_deposito', 'info_moveis.taxa_limpeza']].applymap(lambda x: x.replace('$', '').replace(',','').strip()).astype(np.float64)

C:\Users\eleil\AppData\Local\Temp\ipykernel_31708\1657461863.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  dados[['info_moveis.taxa_deposito', 'info_moveis.taxa_limpeza']] = dados[['info_moveis.taxa_deposito', 'info_moveis.taxa_limpeza']].applymap(lambda x: x.replace('$', '').replace(',','').strip()).astype(np.float64)

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   info_moveis.avaliacao_geral       3162 non-null   float64
 1   info_moveis.experiencia_local     3818 non-null   object
 2   info_moveis.max_hospedes          3818 non-null   int64
 3   info_moveis.descricao_local       3818 non-null   object
 4   info_moveis.descricao_vizinhanca  3818 non-null   object
 5   info_moveis.quantidade_banheiros  3818 non-null   int64
 6   info_moveis.quantidade_quartos    3818 non-null   int64
 7   info_moveis.quantidade_camas      3818 non-null   int64
 8   info_moveis.modelo_cama           3818 non-null   object
 9   info_moveis.comodidades           3818 non-null   object
 10  info_moveis.taxa_deposito         3818 non-null   float64
 11  info_moveis.taxa_limpeza          3818 non-null   float64
 12  info_moveis.preco                 3818 non-null   float64
dtypes: float64(4), int64(4), object(5)
memory usage: 387.9+ KB

Tratando dados textuais

In [29]:
dados['info_moveis.descricao_local']

0       This clean and comfortable one bedroom sits ri...
1       Our century old Upper Queen Anne house is loca...
2       Cozy room in two-bedroom apartment along the l...
3       Very lovely and cozy room for one. Convenientl...
4       The “Studio at Mibbett Hollow' is in a Beautif...
                              ...
3813    Beautiful craftsman home in the historic Wedgw...
3814    Located in a very easily accessible area of Se...
3815    This home is fully furnished and available wee...
3816    This business-themed modern home features:  *H...
3817    This welcoming home is in the quiet residentia...
Name: info_moveis.descricao_local, Length: 3818, dtype: object

In [ ]:
# Convertendo os valores da coluna 'info_moveis.descricao_local' para letras minúsculas e atribuindo de volta à mesma variável
dados['info_moveis.descricao_local'] = dados['info_moveis.descricao_local'].str.lower()

"""O atributo str do pandas é utilizado para acessar métodos específicos de manipulação de strings em colunas de um DataFrame. No exemplo acima, estamos utilizando str.lower() na coluna 'info_moveis.descricao_local' do DataFrame dados para converter todos os valores dessa coluna para letras minúsculas. Isso é útil quando queremos padronizar o formato dos textos, facilitando comparações e análises posteriores. Após a conversão, os valores são atribuídos de volta à mesma coluna, atualizando os dados no DataFrame."""

0       this clean and comfortable one bedroom sits ri...
1       our century old upper queen anne house is loca...
2       cozy room in two-bedroom apartment along the l...
3       very lovely and cozy room for one. convenientl...
4       the “studio at mibbett hollow' is in a beautif...
                              ...
3813    beautiful craftsman home in the historic wedgw...
3814    located in a very easily accessible area of se...
3815    this home is fully furnished and available wee...
3816    this business-themed modern home features:  *h...
3817    this welcoming home is in the quiet residentia...
Name: info_moveis.descricao_local, Length: 3818, dtype: object

In [ ]:
# Removendo caracteres especiais da coluna 'info_moveis.descricao_local' exceto letras, números, hífens, crases e espaços e substituindo por espaço e atribuindo de volta à mesma variável
dados['info_moveis.descricao_local'] = dados['info_moveis.descricao_local'].str.replace('[^a-zA-Z0-9\-\` ]', ' ', regex=True)
dados['info_moveis.descricao_local']

"""O metodo str.replace() do pandas é utilizado para substituir ocorrências de um padrão específico em uma coluna de strings. No exemplo acima, estamos aplicando str.replace('[^a-zA-Z0-9\-\` ]', ' ', regex=True) à coluna 'info_moveis.descricao_local' do DataFrame dados. O padrão '[^a-zA-Z0-9\-\` ]' é uma expressão regular que corresponde a qualquer caractere que não seja uma letra (maiúscula ou minúscula), número, hífen, crase ou espaço. Ao utilizar esse padrão com o parâmetro regex=True, estamos substituindo todos os caracteres especiais que não correspondem a esses critérios por um espaço (' '). Isso ajuda a limpar os dados, removendo caracteres indesejados e facilitando análises posteriores. Após a substituição, os valores são atribuídos de volta à mesma coluna, atualizando os dados no DataFrame.

O regex=True indica que o padrão fornecido é uma expressão regular, permitindo correspondências mais complexas e flexíveis na substituição dos caracteres."""

<>:2: SyntaxWarning: invalid escape sequence '\-'
<>:2: SyntaxWarning: invalid escape sequence '\-'
C:\Users\eleil\AppData\Local\Temp\ipykernel_28736\355528608.py:2: SyntaxWarning: invalid escape sequence '\-'
  dados['info_moveis.descricao_local'] = dados['info_moveis.descricao_local'].str.replace('[^a-zA-Z0-9\-\` ]', ' ', regex=True)

0       This clean and comfortable one bedroom sits ri...
1       Our century old Upper Queen Anne house is loca...
2       Cozy room in two-bedroom apartment along the l...
3       Very lovely and cozy room for one  Convenientl...
4       The  Studio at Mibbett Hollow  is in a Beautif...
                              ...
3813    Beautiful craftsman home in the historic Wedgw...
3814    Located in a very easily accessible area of Se...
3815    This home is fully furnished and available wee...
3816    This business-themed modern home features    H...
3817    This welcoming home is in the quiet residentia...
Name: info_moveis.descricao_local, Length: 3818, dtype: object

In [ ]:
# Removendo hífens isolados da coluna 'info_moveis.descricao_local' e substituindo por espaço e atribuindo de volta à mesma variável
dados['info_moveis.descricao_local'] = dados['info_moveis.descricao_local'].str.replace('(?<!\w)-(?!\w)', ' ', regex=True)
dados['info_moveis.descricao_local']

"""Regex (ou expressão regular) é uma sequência de caracteres que define um padrão de busca em um texto. Ele é uma ferramenta poderosa e versátil que permite encontrar, substituir e manipular padrões de texto de forma eficiente. O regex é amplamente utilizado em diferentes áreas, incluindo programação, ciência de dados e processamento de texto.

Em ciência de dados, o regex é frequentemente usado para processar dados de texto brutos. Algumas dessas aplicações incluem a limpeza de dados, onde o regex pode ser usado para encontrar e substituir certos caracteres. Também pode ser usado em projetos de classificação; um exemplo é usar o regex como auxílio para encontrar padrões no texto de e-mails, o que ajuda a classificar se eles são spam ou não spam."""

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
C:\Users\eleil\AppData\Local\Temp\ipykernel_28736\2191193663.py:1: SyntaxWarning: invalid escape sequence '\w'
  dados['info_moveis.descricao_local'] = dados['info_moveis.descricao_local'].str.replace('(?<!\w)-(?!\w)', ' ', regex=True)

0       This clean and comfortable one bedroom sits ri...
1       Our century old Upper Queen Anne house is loca...
2       Cozy room in two-bedroom apartment along the l...
3       Very lovely and cozy room for one  Convenientl...
4       The  Studio at Mibbett Hollow  is in a Beautif...
                              ...
3813    Beautiful craftsman home in the historic Wedgw...
3814    Located in a very easily accessible area of Se...
3815    This home is fully furnished and available wee...
3816    This business-themed modern home features    H...
3817    This welcoming home is in the quiet residentia...
Name: info_moveis.descricao_local, Length: 3818, dtype: object

In [ ]:
# Transformando a coluna 'info_moveis.descricao_local' em listas de palavras
dados['info_moveis.descricao_local'] = dados['info_moveis.descricao_local'].str.split()
dados['info_moveis.descricao_local']

"""O metodo str.split() do pandas é utilizado para dividir os valores de uma coluna de strings em listas de palavras, com base em um delimitador específico (por padrão, o espaço em branco). No exemplo acima, estamos aplicando str.split() à coluna 'info_moveis.descricao_local' do DataFrame dados. Isso resulta na transformação dos valores dessa coluna em listas, onde cada elemento da lista representa uma palavra separada do texto original. Essa abordagem é útil para análises de texto, como processamento de linguagem natural, onde é necessário trabalhar com palavras individuais para realizar tarefas como contagem de frequência, análise de sentimentos ou criação de modelos de aprendizado de máquina. Após a divisão, os valores são atribuídos de volta à mesma coluna, atualizando os dados no DataFrame."""

0       [This, clean, and, comfortable, one, bedroom, ...
1       [Our, century, old, Upper, Queen, Anne, house,...
2       [Cozy, room, in, two-bedroom, apartment, along...
3       [Very, lovely, and, cozy, room, for, one, Conv...
4       [The, Studio, at, Mibbett, Hollow, is, in, a, ...
                              ...
3813    [Beautiful, craftsman, home, in, the, historic...
3814    [Located, in, a, very, easily, accessible, are...
3815    [This, home, is, fully, furnished, and, availa...
3816    [This, business-themed, modern, home, features...
3817    [This, welcoming, home, is, in, the, quiet, re...
Name: info_moveis.descricao_local, Length: 3818, dtype: object

In [38]:
dados['info_moveis.descricao_local']
dados.head()

,info_moveis.avaliacao_geral,info_moveis.experiencia_local,info_moveis.max_hospedes,info_moveis.descricao_local,info_moveis.descricao_vizinhanca,info_moveis.quantidade_banheiros,info_moveis.quantidade_quartos,info_moveis.quantidade_camas,info_moveis.modelo_cama,info_moveis.comodidades,info_moveis.taxa_deposito,info_moveis.taxa_limpeza,info_moveis.preco
0,10.0,--,1,"[This, clean, and, comfortable, one, bedroom, ...",Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
1,10.0,--,1,"[Our, century, old, Upper, Queen, Anne, house,...","Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
2,10.0,--,1,"[Cozy, room, in, two-bedroom, apartment, along...",The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
3,10.0,--,1,"[Very, lovely, and, cozy, room, for, one, Conv...","Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
4,10.0,--,1,"[The, Studio, at, Mibbett, Hollow, is, in, a, ...",--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00

In [40]:
# Removendo caracteres {, }, " da coluna 'info_moveis.comodidades' e atribuindo de volta à mesma variável
dados['info_moveis.comodidades'] = dados['info_moveis.comodidades'].str.replace('\{|}|"', '', regex=True)
dados['info_moveis.comodidades']

<>:2: SyntaxWarning: invalid escape sequence '\{'
<>:2: SyntaxWarning: invalid escape sequence '\{'
C:\Users\eleil\AppData\Local\Temp\ipykernel_28736\2666430844.py:2: SyntaxWarning: invalid escape sequence '\{'
  dados['info_moveis.comodidades'] = dados['info_moveis.comodidades'].str.replace('\{|}|"', '', regex=True)

0       Internet,Wireless Internet,Kitchen,Free Parkin...
1       TV,Internet,Wireless Internet,Kitchen,Free Par...
2       TV,Internet,Wireless Internet,Kitchen,Free Par...
3       Internet,Wireless Internet,Kitchen,Free Parkin...
4       Wireless Internet,Kitchen,Free Parking on Prem...
                              ...
3813    TV,Cable TV,Internet,Wireless Internet,Air Con...
3814    TV,Cable TV,Internet,Wireless Internet,Kitchen...
3815    TV,Cable TV,Internet,Wireless Internet,Air Con...
3816    TV,Cable TV,Internet,Wireless Internet,Air Con...
3817    TV,Internet,Wireless Internet,Kitchen,Free Par...
Name: info_moveis.comodidades, Length: 3818, dtype: object

In [ ]:
# Transformando a coluna 'info_moveis.comodidades' em listas de palavras
dados['info_moveis.comodidades'] = dados['info_moveis.comodidades'].str.split(',')
dados['info_moveis.comodidades'].head()

0    [Internet, Wireless Internet, Kitchen, Free Pa...
1    [TV, Internet, Wireless Internet, Kitchen, Fre...
2    [TV, Internet, Wireless Internet, Kitchen, Fre...
3    [Internet, Wireless Internet, Kitchen, Free Pa...
4    [Wireless Internet, Kitchen, Free Parking on P...
Name: info_moveis.comodidades, dtype: object

Trabalhando com dados de tempo

A classe datetime é um tipo de dado que representa uma data e hora específicas em Python. Ela permite trabalhar e manipular dados de ano, mês, dia, hora, minuto, segundo e microssegundo, além de dias da semana, como segunda, terça, quarta, etc. Essa classe é definida no módulo datetime e é fundamental na manipulação de datas e horários em Python. Com ela, é possível realizar operações de cálculo de diferenças entre datas, formatação de datas e horas em diferentes formatos, além de ser muito útil em análises de dados que envolvem séries temporais.

In [ ]:
# Lendo o arquivo JSON em um DataFrame e atribuindo a uma nova variável
dt_data = pd.read_json('C:\\Users\\eleil\\OneDrive\\Documents\\GitHub\\Estudo-e-Projetos-Alura\\Python para Data Sciense\\Pandas\\Transformação e manipulação de dados\\moveis_disponiveis.json')
# Exibindo as primeiras linhas do DataFrame
dt_data.head()

    id        data  vaga_disponivel preco
0  857  2016-01-04            False  None
1  857  2016-01-05            False  None
2  857  2016-01-06            False  None
3  857  2016-01-07            False  None
4  857  2016-01-08            False  None

In [ ]:
# Verificando o tipo de dado da coluna 'data'
dt_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  object
 2   vaga_disponivel  365000 non-null  bool
 3   preco            270547 non-null  object
dtypes: bool(1), int64(1), object(2)
memory usage: 11.5+ MB

In [ ]:
# Transformando a coluna 'data' em datetime e atribuindo de volta à mesma variável
dt_data['data'] = pd.to_datetime(dt_data['data'])
dt_data.info()

"""O metodo pd.to_datetime() do pandas é utilizado para converter uma coluna de strings ou outros tipos de dados em objetos datetime. No exemplo acima, estamos aplicando pd.to_datetime() à coluna 'data' do DataFrame dt_data, convertendo seus valores para o tipo datetime. Isso é útil quando queremos trabalhar com dados de data e hora de forma mais eficiente, permitindo operações como cálculos de diferenças entre datas, filtragem por períodos específicos e análise temporal. Após a conversão, os valores são atribuídos de volta à mesma coluna, atualizando os dados no DataFrame.

A classe datetime é uma das mais importantes e amplamente utilizadas para manipulação de datas e horas em Python. Ela representa uma data e hora específicas, combinando informações de ano, mês, dia, hora, minuto, segundo e microssegundo em um único objeto. A classe datetime oferece uma variedade de métodos e atributos que permitem realizar operações como cálculos de diferenças entre datas, formatação de datas em diferentes estilos, extração de componentes individuais (como ano ou mês) e muito mais. Além disso, a classe datetime é fundamental para trabalhar com séries temporais e análises de dados que envolvem datas e horários.

Dentro da classe datetime podemos encontrar diversos métodos úteis, como:
- dt.strftime(): Formata objetos datetime em strings com um formato específico.
- dt.strptime(): Converte strings em objetos datetime com base em um formato específico.
- dt.date(): Extrai a parte da data de um objeto datetime.
- dt.time(): Extrai a parte do tempo de um objeto datetime.
- dt.year, dt.month, dt.day: Acessa os componentes individuais de um objeto datetime.
- dt.weekday(): Retorna o dia da semana como um número inteiro (0 para segunda-feira, 6 para domingo). 
- dt.now(): Retorna o objeto datetime atual.
- dt.timedelta(): Permite realizar operações de adição e subtração de períodos de tempo.    
- dt.to_period(): Converte objetos datetime em períodos (como meses ou anos).
- dt.today(): Retorna a data atual sem a parte do tempo.
- dt.normalize(): Normaliza objetos datetime para a meia-noite do dia correspondente.
- dt.isocalendar(): Retorna uma tupla com o ano ISO, semana ISO e dia da semana ISO.
- dt.tz_localize(): Localiza um objeto datetime em um fuso horário específico.
Essas são apenas algumas das funcionalidades oferecidas pela classe datetime, que é essencial para manipulação de datas"""

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  datetime64[ns]
 2   vaga_disponivel  365000 non-null  bool
 3   preco            270547 non-null  object
dtypes: bool(1), datetime64[ns](1), int64(1), object(1)
memory usage: 11.5+ MB

In [48]:
dt_data.head()

    id       data  vaga_disponivel preco
0  857 2016-01-04            False  None
1  857 2016-01-05            False  None
2  857 2016-01-06            False  None
3  857 2016-01-07            False  None
4  857 2016-01-08            False  None

In [ ]:
# Formatando a coluna 'data' para exibir apenas o ano e o mês
dt_data['data'].dt.strftime('%Y-%m')

"""O metodo dt.strftime() do pandas é utilizado para formatar objetos datetime em strings com um formato específico. No exemplo acima, estamos aplicando dt.strftime('%Y-%m') à coluna 'data' do DataFrame dt_data. O formato '%Y-%m' indica que queremos exibir apenas o ano (Y) e o mês (m) da data, separados por um hífen. Isso é útil quando queremos extrair informações específicas de datas para análises ou visualizações, como agrupar dados por mês ou ano. O resultado é uma série de strings formatadas de acordo com o padrão especificado."""

0         2016-01
1         2016-01
2         2016-01
3         2016-01
4         2016-01
           ...
364995    2016-12
364996    2016-12
364997    2016-12
364998    2017-01
364999    2017-01
Name: data, Length: 365000, dtype: object

In [ ]:
# Agrupando os dados por ano e mês e somando os valores da coluna 'vaga_disponivel' e atribuindo a uma nova variável    
subset = dt_data.groupby(dt_data['data'].dt.strftime('%Y-%m'))['vaga_disponivel'].sum()
subset

data
2016-01    16543
2016-02    20128
2016-03    23357
2016-04    22597
2016-05    23842
2016-06    23651
2016-07    22329
2016-08    22529
2016-09    22471
2016-10    23765
2016-11    23352
2016-12    24409
2017-01     1574
Name: vaga_disponivel, dtype: int64