In [1]:
import pandas as pd

url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv'

dados = pd.read_csv(url, sep=';')

dados.head(10)

  Nome,Idade,Notas,Aprovado
0           Ary,20,7.5,True
1             Ana,18,,False
2        Cátia,27,2.5,False
3        Denis,18,5.0,False
4         Beto,21,10.0,True
5           Bruna,23,,False
6          Dara,21,7.0,True
7        Carlos,19,6.0,True
8        Alice,35,5.6,False
9           Vitor,28,,False

In [11]:
dados.tail(10)

   Nome,Idade,Notas,Aprovado
8         Alice,35,5.6,False
9            Vitor,28,,False
10          Daniel,21,,False
11         Igor,24,4.5,False
12     Sthefanie,26,9.5,True
13         Mirla,25,9.0,True
14           Paulo,37,,False
15        Mylena,29,7.0,True
16           Lucas,33,,False
17         Nadia,34,8.0,True

In [2]:
type(dados) #mostra o tipo do dataframe
dados.dtypes #mostra o tipo de cada coluna do dataframe
dados.shape #mostra o numero de linhas e colunas do dataframe
dados.columns #mostra o nome das colunas do dataframe
dados.info() #mostra o tipo de cada coluna do dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Nome,Idade,Notas,Aprovado  18 non-null     object
dtypes: object(1)
memory usage: 276.0+ bytes

In [10]:
dados.dtypes
dados.info() #mostra o tipo do dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Nome,Idade,Notas,Aprovado  18 non-null     object
dtypes: object(1)
memory usage: 276.0+ bytes

In [12]:
dados.columns #mostra o nome das colunas do dataframe

Index(['Nome,Idade,Notas,Aprovado'], dtype='object')

In [ ]:
dados.describe() #mostra o resumo dos dados do dataframe

       Nome,Idade,Notas,Aprovado
count                         18
unique                        18
top              Ary,20,7.5,True
freq                           1